### ISSUE TITLE
multi-side admin not working under php 5.3 Fast CGI

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#97] opened 2014-10-04 12:33 UTC
_From [tecumseh...@gmail.com](https://code.google.com/u/103128831540387028144/) on November 08, 2010 02:08:12_

What steps will reproduce the problem? Don't know if anyone else has had this issue yet, but in case it helps . . .

I was moving an existing site to a multi-site install of txp on dreamhost.

1. Am using the lastest svn
2. Set up a separate virtual host admin.site2.com 
3. Selected php5.3 fast cgi (it's in beta on dreamhost right now)
4. finished the install.
5. Public side displayed as expected
6. Admin side was blank.
7. Added a plain index.html to make sure subdomain was resolving correctly. It was.
8. Removed index.html
9. Admin was blank again.
8. Changed to php 5.2 fast cgi
9. Admin side works as expected.

What is the expected output? 
The admin login

What do you see instead?
nothing - was blank.

What version of the product are you using? 
Textpattern version: 4.3.0 ( r3458 )

On what operating system?
Debian Linux (Dreamhost) Please provide any additional information below.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=93_

**Comment by philwareham** [comment] 2015-11-10 21:49
Can anyone verify that this is still an issue?

**Comment by philwareham** [comment] 2016-03-23 09:53
Bump?

**Comment by petecooper** [comment] 2016-08-30 09:22
I set this up over the weekend and couldn't reproduce. Tried a bunch of times, no dice. Perhaps a Dreamhost implementation bug?

Also, Textpattern has _really_ changed since 4.3.0...

**Comment by philwareham** [comment] 2016-08-30 09:24
Closing as everything has moved on since PHP5.3 FastCGI and Textpattern 4.3.0. f issue arises again (which I doubt) can be reopened.

**Closed by philwareham** 2016-08-30 09:24 UTC
