### ISSUE TITLE
UX quirk - hyperlink on an active theme

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1421] opened 2019-10-06 19:42 UTC
Tested with 4.8.0-dev.

Visit `/textpattern/index.php?event=skin`, note an active theme has an 'Active' text marker:

![Screen Shot 2019-10-06 at 20 35 23](https://user-images.githubusercontent.com/226578/66274727-6e41be80-e879-11e9-93fe-80e26af5989d.png)

The 'Active' marker is a hyperlink, which leads to `/textpattern/index.php?event=section&step=section_use_theme&skin=theme-name-here` and using the hyperlink throws up an 'Are you sure?' dialog:

![Screen Shot 2019-10-06 at 20 35 27](https://user-images.githubusercontent.com/226578/66274729-74379f80-e879-11e9-853d-fe5420d95983.png)

I end up at the Section list:

![Screen Shot 2019-10-06 at 20 35 31](https://user-images.githubusercontent.com/226578/66274756-b95bd180-e879-11e9-8242-5d9caeb55705.png)

It's not clear to me what action is being taken that I need to be sure of. I can't see any changes that are made, so is the 'Are you sure?' required?

**Comment by Bloke** [comment] 2019-10-06 19:56
Background reading: https://forum.textpattern.com/viewtopic.php?id=50391

Short answer: the potentially destructive nature (i.e. affecting front-end users) of making a theme live requires confirmation of some sort.

How we go about that is probably net yet best realised, as demonstrated in your experience. We should either state what you are agreeing to in the confirmation message and/or state better what just happened in the resulting pop message. And jumping to the Sections panel is probably not ideal.

I think this just comes down to proper wording of the link, the confirmation popup and result.

**Comment by petecooper** [comment] 2019-10-06 19:57
Nice one @Bloke, thank you - will close and defer to link.

**Comment by bloatware** [comment] 2019-10-06 20:45
Currently, when switching themes, txp checks whether the new one contains pages/styles for every section. If they are missing for some section, the latter remains associated with the old theme, to avoid 404. Hence multiple "active" themes are possible, jumping to Sections panel allows for verification. Are we too careful here, should we unconditionality switch all sections to a new theme when asked so?

**Comment by cara-tm** [comment] 2019-11-09 06:32
The "Active" link could gain to have a greater visual differentiation, maybe in bold, when the corresponding theme is active. Actually, it's not so evident in regard of a such important element.

**Comment by bloatware** [comment] 2019-11-10 14:03
I leave wording and styling with our UX department, it's above my pay grade.

**Comment by philwareham** [comment] 2019-11-12 12:02
Sierry, just reading this thread - can you summarise what the 'active' link does? i.e. what is means by stating active and what happens when you click on it? Thanks.

**Comment by bloatware** [comment] 2019-11-12 13:02
Elementary! Clicking on it makes the corresponding theme "live" (i.e. public) for all sections except those using page/style missing in this theme. Hence several themes at once can be "live", each one for some section(s). The "active" link state indicates the theme is "live".

**Comment by philwareham** [comment] 2019-11-12 13:18
So off the top of my head UX-wise, we need an indicator pill (non-clickable) that shows the particular theme is live, and also another link that activates a theme if not live? The two are not interchangeable.

**Comment by bloatware** [comment] 2019-11-12 13:52
Probably, though this removes the possibility to make live for *all* sections a theme that is live for *some* sections.

**Comment by wion** [comment] 2019-11-30 16:42
I'm writing this doc on using the functionality and still trying to iron it all out for myself...
https://docs.textpattern.com/themes/front-end-themes
So please keep me informed of any UI changes.

I understand the blue 'Active' links as a 'theme switcher' for changing one theme for another across the entire site. Click a blue link, confirm, and the theme switches. The blue link turns green, and the former green link turns blue. I get that. I like the idea of a convenience/easy **theme switcher**. However, having the text 'Active', even if blue, to indicate Inactive, is not ideal. Can you simply make blue 'Active' links read 'Inactive'? That might solve that confusion.

But I have a question. In those cases where you have to manually assign themes to sections in order to use multiple themes at once, do the 'Active' links on those theme in the themes table then turn green? If not, then that green status is failing there too, because it should be a way to easily/quickly see what themes (plural) are active. Logically.

I have a question regarding the green 'Active' status

**Comment by Bloke** [comment] 2019-11-30 16:49
Yeah, the concept of "active" is a bit strange since you can have assets from multiple themes active on different Sections. We'll need to come up with something sharpish in the code to make this a bit more understandable.

Suggestions welcome.

**Comment by bloatware** [comment] 2019-11-30 17:01
Call it 'in use'?

**Comment by wion** [comment] 2019-11-30 17:12
> Call it 'in use'?

You mean the green link? That doesn't solve the problem, I think, because the blue link still reads 'Active'. The blue link text is the problem.

**Comment by wion** [comment] 2019-11-30 17:14
This makes sense to me:

Blue: 'Activate'
Green: 'Active'

You even get the verb command on the blue.

**Comment by bloatware** [comment] 2019-11-30 17:50
> 
> 
> But I have a question. In those cases where you have to manually assign themes to sections in order to use multiple themes at once, do the 'Active' links on those assigned themes automatically turn green?

Yes, it turns green (only) when assigned to some sections (see `Sections` column). I'm fine with Active (which actually means in use) and Activate. Hope that `active` strings already present in db fit in all languages.

**Comment by Bloke** [comment] 2019-12-06 14:29
Is this now fixed to everyone's satisfaction with the active/activate split? If so, we can close this and just add the 'activate' string to the `skin` (or `admin-side` or `common` if we think it might have broader appeal) group.

**Comment by philwareham** [comment] 2019-12-06 15:18
I still don't get how this all works sorry. I've uploaded a couple of themes to test it.

### User flow

1. On theme panel. I have the original (default) theme - with an 'Active' link next to it. I click that link and it drops me into the section panel (via a "Are you sure?" dialog). I’m *not* sure what is changing by clicking that link but I proceed anyway.
2. *Scratches head*. I go back to theme panel.
3. I click on the 'Activate' link next to my additional theme that I imported. "Are you sure?" dialog. I think I'm sure I want to activate it. It drops me into the section panel again.
4. I notice that the 'default' section may now be using the additional theme (although it's not obvious, as the theme column has greyed out text for that theme name even though that's the one that is in use, according to the edit pane).

### The UX issues

- There doesn't seem to be a need for the "Are you sure?" if you clink on the 'Active' link (there is a need if clicking on the 'Activate' though,. as this changes the default section to use it).
- The 'Theme' column on the section list table - greyed-out/non greyed-out entries - I don't know why the theme in use for that section is the one greyed-out.

**Comment by Bloke** [comment] 2019-12-06 16:08
Brief overview:

* With only one entry in the Themes/Pages/Styes column, that is what is Live for everybody - public and development (logged-in) users.
* Greyed-out entries are those that are Live for public visitors, with the darker assets being those that logged-in users see, as they are 'overriding' the greyed-out entries for anyone logged in.
* Using the _Developer preview_ multi-edit option will allow you to set the current Dev (black) assets to replace the current Live (grey) assets for the selected sections. Or, you can 'ditch' the override by using _Reset to Live_ which will then make the chosen Sections have only one assignment for Live and Dev (logged-in) users.
* From the Themes panel, you can apply an entire theme to ALL sections in one fell swoop by clicking either:
** _Preview_ Which sets the theme as a Dev theme for logged-in users, leaving Live unaffected.
** _Activate_ Which sets the theme as Live theme for public visitors, leaving Dev unaffected. Since this changes the public site, it's behind an are-you-sure. Once you do that, one or more themes on the Themes panel will shows as 'Active'.

Now, the caveat is that clicking Preview/Activate will _only affect Sections that won't cause massive breakage_. So if Section A and B were previously assigned the 'archive' Page and you clicked _Activate_ against "Phil's Theme", but your theme didn't have an 'archive' Page asset, the Theme would skip Section A and B, leaving their assignment unchanged. But it _would_ apply the theme to any Sections that already had an 'archive' set, from any theme.

I presume if you click 'Active' that it tries again, since you may have done some assignments in the meantime and want to apply the theme again _Dunno_. Can't think of a use case right now, maybe @bloatware can?

If we can demystify this in any way, great.

**Comment by Bloke** [comment] 2019-12-06 16:17
Jumping to the Sections panel when you use preview/activate is a _little bit_ disconcerting though. I presume it's impossible but maybe a better workflow might be something like Phil suggests where we have a single link on the Themes panel called, I dunno, maybe 'Activate' is right. This would:

* Jump to the Sections panel.
* Pre-select all the themes that this theme _could potentially affect_.
* Pre-select the _Developer preview_ multi-edit option.

So all you have to do then is check the selected sections are as you like, choose whether you want the assets to be migrated from Dev->Live (Deploy to Live) or ditch the Dev (Reset to Live) and then confirm. Yes it's a few more clicks, but it's more transparent. Just not sure if it's possible to do that as there's some JS involved.

**Comment by bloatware** [comment] 2019-12-06 16:38
Yep, probably what @Bloke suggest is less obscure. We'd need only one `Select` link on Themes panel that would take us to Sections panel with all sections preselected and `Change theme` widget open with both `Development` and `Live` options checked. Click on `Go` button and that is it.

**Comment by Bloke** [comment] 2019-12-06 16:47
Uhhh yeah, 'Change theme' multi-edit open... that's what I meant. Ummm, what he said ^^

**Comment by wion** [comment] 2019-12-07 18:36
FWIW, in Phil’s user flow, where he clicks Active link, then...

> 2) Scratches head. I go back to theme panel.

I don’t see why that should be a link at all. If it was just a green Active text indicator (no hot link), that’s clear and functional enough. If anyone actually wanted to be in the preview of the live theme, they would just use the Preview link instead, which is a lot more obvious on the label. 

Seems to me taking the link off is a decent and easy win at _preventing_ at least _some_ confusion to begin with.

**Comment by wion** [comment] 2019-12-07 18:38
Sometimes fewer roads to the doghouse are, in fact, better.

**Comment by bloatware** [comment] 2019-12-07 21:48
The number of associated sections is already an indicator. The link was meant to quickly switch live themes, but if it's head scratching, I can merely remove it and basta. I would just try first what @Bloke suggests in few comments above.

**Comment by wion** [comment] 2019-12-08 00:04
Yes, as I understand it, the blue Activate links were meant to quickly switch a theme. That made sense to me. What I didn’t understand was why the green Active indicator had a link on it.

But maybe you guys are changing it now? Getting rid of the Active/Activate links entirely. I can’t tell.

I’ll wait and see how it turns out in the development demo site. ;)

**Comment by bloatware** [comment] 2019-12-08 10:03
> What I didn’t understand was why the green Active indicator had a link on it.

Because of [this](https://github.com/textpattern/textpattern/issues/1421#issuecomment-559994358), but then it reflexes the complexity=flexibility of txp themes model.

**Comment by bloatware** [comment] 2019-12-10 11:56
Any [better](https://github.com/textpattern/textpattern/commit/6179e2d64638631a88094fda8eafd67e7ff1fcef)? Then I guess it could replace theme `Preview` link too.

**Comment by philwareham** [comment] 2019-12-10 12:23
Getting better I think, like that the link now goes to an actual action on the section panel.

However, I think we could ditch the preview link, and refactor slightly like so...

<img width="559" alt="Screenshot 2019-12-10 at 12 21 26" src="https://user-images.githubusercontent.com/413665/70529116-b2865f00-1b47-11ea-9a43-386bce71c810.png">

...where the 'In use' is not a link, just textual information. Obviously you can have more than one theme in use.

**Comment by philwareham** [comment] 2019-12-10 12:45
[HTML example fo the above](https://design-patterns.textpattern.com/mockups/presentation-skin.html)

**Comment by wion** [comment] 2019-12-10 13:06
I still don't understand why you need to see a 'Select' link on an active (in use) theme. If that given theme is active, why would someone want to select it? What is the beneficial task that clicking 'select' on an active theme provides?

And if there is a purpose, then I would not suggest a blue 'Select' link because it conflicts with the communication of the same color/command on non-active themes. In the case of active themes, I would expect to see a different color/command that shows the alternate state of the theme, for example...

![Inspect with check](https://wion.com/images/temp/inspect-check.png) 

![Inspect only](https://wion.com/images/temp/inspect.png)

**Comment by philwareham** [comment] 2019-12-10 13:11
Maybe 'Assign' instead of 'Select'.

I slightly disagree with colouring any links though. Our UI (hopefully) has consistent colour for links and I prefer to keep that model throughout.

**Comment by wion** [comment] 2019-12-10 13:11
Not sure why those images don't show up. The paths are correct. The images are there.

**Comment by philwareham** [comment] 2019-12-10 13:12
> Not sure why those images don't show up. The paths are correct. The images are there.

You can drag/drop images to a GitHub post and it'll upload them to their CDN. Handy tip.

**Comment by wion** [comment] 2019-12-10 13:17
Thanks. This seems to be a different problem I don't understand. They don't even show up in the browser...
https://wion.com/images/temp/inspect-check.png

Gah, facking web

**Comment by wion** [comment] 2019-12-10 13:27
Anyway, you can see that if the word is different you don't need the check mark or the color, but the color makes a nice distinguishing touch anyway for sighted users.

**Comment by wion** [comment] 2019-12-10 13:31
But again, I don't understand the point of a link on an active theme's 'Select' word. So no link would even be needed, on a different distinguishing word, right?

**Comment by Bloke** [comment] 2019-12-11 10:43
This is definitely getting closer. A couple of notes:

1) When you click 'Select', I like that the default action is to leave Page and Style dropdowns empty, which seems to mean "leave them alone and only change the ones that match the assets already in place". But I now wonder about the sanity of checking all sections, only to have it report that it has only changed one or two out of those selected. I guess that's 'correct' behaviour and I can't think of anything better, just something we need to be aware of and document.

2) When you click 'Select' it only selects the first page of results. If you have more than 12 Sections, the others aren't selected with default pagination. Can we temporarily override the pagination in the 'Select' link without it affecting the user's stored value? I doubt anybody will have more than 96 sections so we're probably safe to override the value to this. If they do have more than 96 sections, they've probably got more problems with site architecture and usability than worrying about switching a theme!

**Comment by philwareham** [comment] 2019-12-11 10:51
> I still don't understand why you need to see a 'Select' link on an active (in use) theme.

@wion I believe that you can mix and match themes per section of site. So, say, you could use theme1 for section1 and default section, and theme2 for section2, etc. In that sense, although a theme is active (used for at least one section of a site) you can still 'Select' other sections for it to be/not to be used in.

**Comment by bloatware** [comment] 2019-12-11 11:35
Hmm, yes, pagination again... It becomes too complicated, I prefer like it was before.

**Comment by Bloke** [comment] 2019-12-11 12:46
Yes, I think it probably worked better. Just need to figure out what to do with the labelling and that odd 'jump' to the Sections page, which was a little jarring/unexpected.

**Comment by bloatware** [comment] 2019-12-11 14:09
The jump was intended to show you the result. Or rather it was easier to code :-)

**Comment by Bloke** [comment] 2019-12-11 14:18
Yes, and it's the right thing to do. we do have precedent for jumping to other pages from links (e.g. the article numbers on the Sections panel) but there it's kind of more obvious that when you click a number you'll see the associated articles.

When clicking a 'preview' link or 'activate' or whatever, it's not immediately obvious that we'll be directing people to another page so I think that's where the cognitive disconnect occurs. As I say, I'm not sure how to get round it.

One more possible spanner: the fact that a theme is Active is reflected by the fact its asset count in the Pages column is > 0. So if you wanted to see which were active, do we even need the 'Active' indicator at all? Yes, it's a convenient visual reminder, but you could sort by the Pages column to put all active themes at the top of the list.

Just playing devil's advocate here if the 'active' thing is causing confusion: we have the option to remove it and still show people what's in use, albeit indirectly.

Does that help or make things murkier?

**Comment by bloatware** [comment] 2019-12-11 14:40
You mean `Sections` column, right? Yes, and I've played with its presentation (hide 0 values, make bold, etc), but it's not as immediately noticeable.

**Comment by Bloke** [comment] 2019-12-11 14:47
Sorry, yeah, Sections column (I've amended the post).

We could try moving the column. Not sure if it'll help. I mean, people can already hide the 'Name' column as long as it's not currently being used for sorting, so the active/preview/blah blah disappears. Then the only way they could change things is via the multi-edit on the Sections panel.

Are we overthinking this? Are we trying to add too many "roads to accomplish something" when we could find a simpler way, perhaps?

**Comment by bloatware** [comment] 2019-12-11 14:59
A switch for 'live' theme is handy, the rest is decoration.

**Comment by wion** [comment] 2019-12-11 15:16
> you can mix and match themes per section of site

Oh, right. Of course I knew you could do this, but it was this particular entry point that always trips me up. I know that if I was to ever mix/match themes (doubtful), I would not take this path; rather, I'd just go to the Sections panel from the top, or whatever, and apply a given theme to each section. I would avoid this entry from an active theme because it doesn't make any sense to me in that context.

Maybe we need to be asking what new users of Txp think. I'm too jaded in my habits at this point.

**Comment by wion** [comment] 2019-12-12 12:19
This is what I'm seeing now in the demo...

![4 point 8](https://wion.com/assets/images/temp/4p8.png)

For the 4 point 8 (default) theme -- presumably the one _active_, though only the green color indicates as much -- when I click either the 'Preview' link or the green 'Select' link, they both take me to the same place with the same selection controls indicated.

Assuming I'm not mistaken there, that's the desired result? If so, it seems odd to me, because have two links ('Preview' and 'Select') bearing different text labels doing the exact same thing from the same location is not intuitive at all. 

But, if the green-linked word, 'Select', was instead a regular black (non-linked) word, 'Active' -- and ditto for any other active themes -- it would make perfect sense to me in relation to non-active themes.

![4 point 8](https://wion.com/assets/images/temp/4p8active.png)

Dark mode...

![4 point 8](https://wion.com/assets/images/temp/4p8activedark.png)

What am I missing?

**Comment by bloatware** [comment] 2019-12-12 14:47
@wion while `Preview` effectively (and unconditionally) *makes* the theme `dev`, `Select` only *preselects* it and leaves the decision with you. But this looks inconsistent, I agree, so one of these likns will be changed.

**Comment by wion** [comment] 2019-12-12 14:53
Phil was talking about the Sections panel context for previewing a development theme, [from here](https://github.com/textpattern/textpattern/issues/1421#issuecomment-562612912):
> 4. I notice that the 'default' section may now be using the additional theme (although it's not obvious, as the theme column has greyed out text for that theme name even though that's the one that is in use, according to the edit pane).

The appearance of two names is a tad confusing at first, but I think part of it is the way it appears in the cell. For example, the wrapping lines that break the name of the development theme in context, and the fact it's not on top.

What about showing names on separate lines (e.g. `<br>`) and putting the active (greyed-out) theme under, which somewhat fits the mental notion that it's working _under_ the theme in context of being previewed...

![Sections dev preview](https://wion.com/assets/images/temp/sections-light.png)

![Sections dev preview](https://wion.com/assets/images/temp/sections-dark.png)

If an icon doesn't make sense, let the 'active' idea follow through from the themes panel...

![Sections dev preview](https://wion.com/assets/images/temp/sections-dark-active.png)

**Comment by wion** [comment] 2019-12-12 15:27
> while `Preview` effectively (and unconditionally) _makes_ the theme `dev` . . .

_That_ is the bit I kept missing! It finally clicks. Thank you.

So, yeah, 'Preview' is not a good word there, in that case. The word is what kept throwing me. We need a link word, or two short ones, that communicates what you just said... _Making_ that change.

Since all of this is about theme development, what about using 'Dev mode' instead of 'Preview'? Or something in that direction. If I see a link like that, it's pretty suggestive that if I click it, I'm going to initiate what it says.

I don't like the abbreviation of 'dev', but it's probably clear. 'Design mode'?

**Comment by wion** [comment] 2019-12-12 15:51
> while Preview effectively (and unconditionally) makes the theme dev, Select only preselects it and leaves the decision with you.

Now that I think about it, the resulting action seems oppositely labeled. It would make more sense the other way:

* Click 'Preview', and you've _not_ made anything happen; you're just checking it out, _previewing_. The decision still needs followed through with.
* Click 'Select', however, and you have selected to go down the rabbit hole and _make_ it happen.

**Comment by bloatware** [comment] 2019-12-12 22:20
I'm fine with `<br />` instead of ` | `, can do on the next round.

**Comment by wion** [comment] 2019-12-13 07:22
> Then `<td />` should probably be vertically aligned to top.

Yeah, maybe. If it's never going to be more than two lines, it probably doesn't matter.

I'd even say use the `<br />` in the Section table's Name column, and any other narrow column that uses `|` and has to wrap. Unless the column is wide enough to let all the items separated by `|` flow on a single line, it doesn't look good.

**Comment by wion** [comment] 2019-12-13 09:03
Bloke said:

> Are we overthinking this? Are we trying to add too many "roads to accomplish something" when we could find a simpler way, perhaps?

Yes, I sometimes think there are too many roads to do the same thing and it becomes confusing. In this context, dealing with themes from the Themes panel, I think there should be one path for each of these things:

1. Switch a single them on for the whole site
2. Preview a theme in dev mode, from there you can also make live if you decide to.

But for setting multiple themes on different sections? I would not try to automate that path from the Themes panel. I'd leave that to the Sections panel once a user either previewed or simply went to the sections panel by some other normal route (e.g. via the nav menu).

With that in mind, and carrying the pill box idea back to the Themes panel... 

![Sample view button](https://wion.com/assets/images/temp/themes-dark-pills-switch.png)

'**Preview**' in this case is _not_ making anything happen, it's just previewing the current assignment of the theme and assets to sections, whether development or live.

'**Switch on**' is the act of _making something happen_. Intuitively this would be making the theme the active live theme for the whole site, and you don't go anywhere. Done. But, it could be, as I think you originally wanted, making it active _dev mode_, and putting you in the Section panel with all the gadgets pre-selected and aligned as expected. Whatever. But then you have the seemingly redundant 'preview' conundrum again.

'**Active**' is suggesting that theme is active on the front-end. It could be one or multiple themes in that state.

I'm not saying you should do it this way, I'm just saying this is what makes sense to me. But maybe it helps you find another way.

**Comment by philwareham** [comment] 2019-12-13 09:25
The above is closer to what makes sense to me too! I can implement pill boxes if that is a route you all want to pursue? (it's in my framework, just not included in the Hive/Classic themes presently).

**Comment by phiw13** [comment] 2019-12-13 09:27
Yet another variant of link-button?

**Comment by philwareham** [comment] 2019-12-13 09:30
My preference is just for pills only for non-clickable alerts - kind of in-between the current coloured `alert` text and full-blown `alert-block` region. Links I'd like to keep as consistently as possible.

**Comment by wion** [comment] 2019-12-13 09:34
The presentation is not my concern. I'm just trying to make sense of the functionality. And, yes, I'm saying the breaking `|` on wrapping cell contents is ugly. However that's _made_ to _look_ better, just do it. ;)

**Comment by Bloke** [comment] 2019-12-13 09:36
Pill boxes look nice. Less weight than a full button so don't overwhelm the interface. And much better than the pipes when wrapping on small screens. We could fairly easily thrust this to other panels that do the same thing if we like it (e.g. the Files panel's file_name | view | download).

As for Destry's other points.

* Love the idea of the 'active' (greyed out) theme being shown second, _under_ the one that's overriding it. Simple but effective.
* The "(active)" suffix is handy and we could try that, but it might not be necessary if swapping the order of the themes in that column is intuitive enough. We can gauge it.
* Not sure if we can do the "Would you like to see section assignments?" popup and make it do something meaningful. I guess it's just a dialog box but I think JavaScript only has OK/Cancel actions, which is damned annoying. So the 'OK' could jump to the Sections panel, but 'Cancel' implies "Don't do it" which isn't the case here, we want to do the action but not jump.

**Comment by wion** [comment] 2019-12-13 09:58
>  Not sure if we can do the "Would you like to see section assignments?"

You don't _have_ to have the popup. As long as a user can see, relatively soon, that the 'Switch on' and 'Active' states have changed, that's confirmation by itself that what the expected to happen, did. In that case you could have a confirmation pop-up saying, something like, '_The {name] theme is now live!_' That alone would inspire someone to investigate around more to see how things worked out.

**Comment by Bloke** [comment] 2019-12-13 10:16
> wouldn't this just be another case of a green 'Success' popup from the bottom of the screen?

I think it does (did) that anyway. But the message was worded as if you'd performed the action on the Sections panel via the multi-edit. I think that's a by-product of us 'jumping' to this screen, selecting the sections and doing that action on behalf of the user. Not sure we can get round that and override the message with anything more "themeish" after the jump.

**Comment by wion** [comment] 2019-12-13 10:25
Maybe you hide the 'success' message in this context and provide a mid-screen popup one that confirms the live status?

**Comment by wion** [comment] 2019-12-13 12:28
>   The "(active)" suffix is handy and we could try that, but it might not be necessary if swapping the order of the themes in that column is intuitive enough. We can gauge it.

Just to point, the reason I introduced that idea was because the greyed-out name by itself was not as clear, [as suggested](https://github.com/textpattern/textpattern/issues/1421#issuecomment-565039730). When I first saw it, it didn't make sense immediately either. Not until I started drafting the Themes doc did I understand better. So, by have the suffix, it makes it perfectly clear what it is, and what state it is in. The greyed-out design is merely keeping it unobtrusive in this context, if you will.

Is it possible to A/B test development? ;)

**Comment by Bloke** [comment] 2019-12-13 12:32
Understood. If it adds clarity and doesn't clutter, I'm all for it.

The only way to A/B test is to break out a branch. Set master to use one method, then the branch as the other and hop between them to see the differences. Not exactly classic split testing!

**Comment by wion** [comment] 2019-12-13 12:37
> If it adds clarity and doesn't clutter, I'm all for it.

I guess if it was explained in a convenient pophelp, that might allow leaving the suffix out. But a one-word suffix in context versus a short yet multiple-word explanation out of context... Seems obvious which way to fall.

**Comment by wion** [comment] 2019-12-13 12:54
Another idea regarding how to handle the suffix, but still deliver the message...

![Live theme indicator](https://wion.com/assets/images/temp/sections-dark-live-indicator.png)

**Comment by Bloke** [comment] 2019-12-13 12:57
Oooh yeah, that works too. And it's cleaner.

**Comment by wion** [comment] 2019-12-13 14:48
Just to think about the diction. If you go with the 'live' idea, then you probably want to start with something like this at the themes panel...

![Make theme live](https://wion.com/assets/images/temp/themes-make-live.png)

'Live' is perfectly clear, and probably the shortest word you'll dig up.

'Make live' is the clearest verb action to becoming 'live'.

If you say 'Switch on', for example, you've changed out of the clear relationship. In that case you might have 'Switch on' and 'On'. But then what does '"On" mean exactly?' Someone might wonder.

'Live' is more universally clear, I think.

I won't quibble about what words you actually use, but I think you want to make sure they are logically paired and the concept transfers between panels.

**Comment by bloatware** [comment] 2019-12-13 15:26
I guess we will simply remove this 'live' link - nothing seems fully satisfactory.

**Comment by wion** [comment] 2019-12-13 15:50
Sure. In fact, no need to have the word 'Live' in the Theme table when nothing there means the same thing.

**Comment by petecooper** [comment] 2019-12-16 19:12
I've gone back and forth on whether I should've opened this issue, but with nearly 70 replies it was clearly worth raising.

What's the general consensus? Is there still to-and-fro or are we at a natural 'done' stop point?

**Comment by bloatware** [comment] 2019-12-16 19:34
Still cooking, please wait.

**Comment by philwareham** [comment] 2019-12-16 20:26
I’ve got a couple of things to try to, related to the new pill style I landed earlier today.

**Comment by philwareham** [comment] 2019-12-17 16:51
I know we are going in circles slightly, but I've been testing in my theme mockups:

<img width="541" alt="Screenshot 2019-12-17 at 16 46 35" src="https://user-images.githubusercontent.com/413665/71016304-e2f06f00-20ec-11ea-9704-294930f1a50b.png">

See https://design-patterns.textpattern.com/mockups/presentation-skin.html for HTML - you'll see 'In use' is *not* a link, just an indicator.

We can follow this UI through to other panels if wanted, i.e. to show which pages are in use (although this might be overkill).

**Comment by wion** [comment] 2019-12-17 17:32
Looks okay to me.

Can you do a mock of what it looks like when clicking the 'Assign sections' link for the bootstrap-blog theme? ;)

**Comment by philwareham** [comment] 2019-12-18 10:36
> Can you do a mock of what it looks like when clicking the 'Assign sections' link for the bootstrap-blog theme? ;)

Sure:

<img width="812" alt="Screenshot 2019-12-18 at 10 29 39" src="https://user-images.githubusercontent.com/413665/71078801-fe598980-2181-11ea-9742-0cf45dcb2d1d.png">

Currently exactly like clicking the 'Select' link in the dev branch. That is still up for debate though, if that dropdown link can be made to work in a satisfactory way as discussed previously by others, I'm OK with it. Or with any other suggestions on how you assign sections upon clickthrough from a theme (I can't think of any other method at this time).

**Comment by wion** [comment] 2019-12-18 10:50
I didn't mean the 'Select' link, but rather, when previewing a dev theme. What I wanted to see was in dev preview mode and how the dev and live theme names would be handled, for example...
https://github.com/textpattern/textpattern/issues/1421#issuecomment-565431314

In the demo site, the live theme name is now crossed-out (has a line through it). Is that final design, then?

The reason I'm asking these questions is because I'm trying to get the Themes doc finished and I can't until this is all finalized. Somebody just let me know when it is, and updated in the demo, so I can test it all.

**Comment by petecooper** [comment] 2019-12-18 10:57
Aside: as of the next scheduled rebuild (1200UTC, about an hour from the timestamp of this comment), `dev-demo` will have a writable `themes` directory, given the stage of development and continued interest in this issue.

If Bad Things happen, I'll switch it back…but let's not dwell on that.

**Comment by philwareham** [comment] 2019-12-18 11:27
> What I wanted to see was in dev preview mode and how the dev and live theme names would be handled

Oh, I see what you mean. OK how about this?...

<img width="531" alt="Screenshot 2019-12-18 at 11 22 49" src="https://user-images.githubusercontent.com/413665/71082355-dfaac100-2188-11ea-87b3-a6d748ce978a.png">

Doesn't seem to be a need to put live on sections without dev/live in action - unless you can have a section that is only set on dev too (i.e. not live)?

On that note, I notice there is no way to set dev and live directly in the section edit panel - only by using the 'With selected...' dropdown on the section list panel. I guess that is intentional to avoid any added confusion?

**Comment by wion** [comment] 2019-12-18 11:46
Now, we're getting there. ;)

I would suggest using the same 'In use' pill from the Themes panel so the concept logically carries over to the Sections panel consistently.  Or change it to 'Live' in the Themes panel. But just so it's consistent.

I'd also vote, my opinion only, that just using 'Dev' here, instead of the longer word, 'Development', would be fine.

> Doesn't seem to be a need to put live on sections without dev/live in action - unless you can have a section that is only set on dev too (i.e. not live)?

It's about context, and how you came to the Sections panel from the Themes panel. If you followed a 'Preview' link on a non-live (in use) theme, you arrive in the Sections panel in Dev context and see the two theme names as here. The non-greyed out name implies 'development' (in context of the view). The greyed-out name implies 'live' (underneath the current dev context).

If your arrive to the Sections panel via a Preview link on a live (in use) theme in the Themes panel, then you are not in Dev mode, but Live mode, so there will be no double showing of theme names under the Theme column.

> I notice there is no way to set dev and live directly in the section edit panel - only by using the 'With selected...' dropdown on the section list panel. I guess that is intentional to avoid any added confusion?

Yes. But you can also set just the live theme per section at a time by clicking a section name and changing the theme assignment that way. But, yes, the _encouraged_ path for doing this seems to be via the selection controls (i.e. 'With selected' drop-down), as I understand it.

**Comment by wion** [comment] 2019-12-18 11:59
In fact, I don't think you need the 'Development' indicator if you think about which theme you click that brings you to the Sections panel. If you click a Preview link on a dev theme, you're already in dev mode context. Does that need to be further highlighted more than a regular appearing name?  

The former greyed-out indication on live names was getting close to the distinction, but just lacking a more clear meaning of 'live', I think. The trick, though, is you don't want to bring too much attention to the live state because that's not the context in this case. That's why i think the greyed-out approach worked better. It downplayed the out-of-context theme. Make sense?

**Comment by philwareham** [comment] 2019-12-18 12:12
> I would suggest using the same 'In use' pill from the Themes panel so the concept logically carries over to the Sections panel consistently. Or change it to 'Live' in the Themes panel. But just so it's consistent.

A theme can be 'in use' but not specifically 'live' though, so I think should keep both texts in their respective panels.

> I'd also vote, my opinion only, that just using 'Dev' here, instead of the longer word, 'Development', would be fine.

We already have the translation string 'development', hence why it's used in my example. Also I feel 'dev' doesn't translate well across languages (although, yes, we know the term well in English).

> In fact, I don't think you need the 'Development' indicator if you think about which theme you click that brings you to the Sections panel. If you click a Preview link on a dev theme, you're already in dev mode context. Does that need to be further highlighted more than a regular appearing name? Maybe. Maybe not.

My proposal was to remove the 'Preview' and 'Select' links entirely and have that covered by the 'Assign sections' link instead. On assignment the user can decide whether they want the section's theme to be dev, live, or both. So in that sense I vote to use the 'Development' pill indicator.

**Comment by wion** [comment] 2019-12-18 12:55
> A theme can be 'in use' but not specifically 'live' though

I had not considered that distinction before. Obviously still missing in my understanding/model of all this.

> We already have the translation string 'development'

Fine. I'm not aware of all the back-end hookups. Whatever needs to be.

> On assignment the user can decide whether they want the section's theme to be dev, live, or both.

Okay, so that's what you mean, then, and where the change actually happens. In fact, there's four possible states?

1. Live
2. Dev
3. Both
4. Neither

**Comment by philwareham** [comment] 2019-12-19 09:54
I've committed a couple of amends to the workflow to dev branch based on my suggestions above. Please try it out and see if that is closer to the end goal now. I still need to think about the UI for when a theme page assigned to a section has issues (currently I think it has some error classes and `del` tags but I need to play with it a bit more. Thanks for your patience.

BTW I have only commented out portions of code, so we can revert quite easily if you don't like my test.

**Comment by Bloke** [comment] 2019-12-19 10:14
Much clearer, thanks Phil. Having the Assign Sections jump to the sections pane is no longer a jarring UX - because you expect it - and having it auto-select the Change theme/page/style with both dev and live pre-checked makes sense to me and saves a few clicks. Not sure if we're going to get a better workflow right now so I'm happy with this.

Of course, if you change to page 2 or 3 to check sections for assignment, the multi-edit resets to its unselected state, but there's not much we can do about that and is unlikely to affect many people anyway. Few sites in the wild will have > 12 sections, I expect.

One minor thing - and I'm not sure if there's a solution besides using an `sp` - is if you have all columns displayed on a smallish desktop (possibly mobile too) this is what you see:

![Screen Shot 2019-12-19 at 10 00 54](https://user-images.githubusercontent.com/21252/71164560-42fb2880-2247-11ea-802a-e9552589e095.png)

To me, that's unclear if the 'Development' pill is a sort of 'heading' that refers to the item beneath it or is attached to the thing above. If I hide a few columns, it pops up alongside the top theme, where it makes things clearer.

Anything sensible we can do about this? Or is it one of those things we have to live with. I dislike sticking nbsp everywhere as it makes things wider than necessary - especially if your theme name is long - but I don't see any other obvious way to disambiguate this.

Thoughts?

**Comment by philwareham** [comment] 2019-12-19 10:16
> Thoughts?

Yeah, I can improve that I think. Leave it with me.

**Comment by philwareham** [comment] 2019-12-19 10:49
> Yeah, I can improve that I think. Leave it with me.

OK, there is a `hr` between them now in latest dev, which is semantically correct to use here I think.

**Comment by Bloke** [comment] 2019-12-19 10:52
Works for me. Nice one!

**Comment by philwareham** [comment] 2019-12-19 11:44
OK, I've put an indicator on the section list now when a theme's page isn't available to a section. And I see Oleg has made an update to pre-check all checkboxes when 'Assign sections' is clicked.

So, I'm personally happy with the UX of this now. Please feel free to close if/when you have checked and confirmed it is to your liking. Cheers!

**Comment by bloatware** [comment] 2019-12-19 11:45
All sections are preselected now, whatever pagination value.

**Comment by Bloke** [comment] 2019-12-19 11:59
Nice indicators and pagination trick.

**Comment by philwareham** [comment] 2019-12-19 14:26
Closing this one. If you spot any serious flaws then please re-open. Thanks everyone!

**Comment by Bloke** [comment] 2019-12-20 22:31
Oopsie. Bug:

* Visit Sections panel.
* Edit any section details.
* Save.

Expected result: return to Section list as normal, paginated.

Actual result: Section list displayed with all sections selected, all sections on display and the change page/form/style multi-edit open.

**Comment by bloatware** [comment] 2019-12-20 22:50
Bad name choice, sorry. Should be fixed now.

**Comment by Bloke** [comment] 2019-12-20 23:10
Thank you, and sorry this one's dragged on!

**Closed by Bloke** 2019-12-20 23:10 UTC
Labels: themes, usability
