### ISSUE TITLE
`<txp:text />` strangeness in 4.6-dev

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#495] opened 2015-07-08 14:25 UTC
It appears that `<txp:text />` might be broken. I'm using 4.6-dev (16a3defd174b65d300d278d153a4bc52) and noticed it with the sidebar/aside on the right where `links` is not capitalised. The code for that text is:

```
<txp:text item="links" />
```

I checked that `links` is capitalised in the included en-gb Textpack - it is. I updated the en-gb Textpack to July 7th - it's still capitalised. I tried <txp:text item="linkscategory" /> to test if it was just that string that's broken - it's not. I put `<txp:text item="links" />` into an article body and that outputs `links` - no capitals. I tried `<txp:text item="foo123" />` and that outputs `foo123`, so it appears that the `item` attribute isn't working correctly with `<txp:text />` and it just inlines the provided value instead.

**Comment by Bloke** [comment] 2015-07-08 15:47
Not a bug, as such, but unintuitive behaviour. Try displaying this:

    Permlink: <txp:text item="permlink" />
    Permlink mode: <txp:text item="permlink_mode" />

You'll notice that `permlink` is capitalised, whereas `permlink_mode` is not, even though they are both capitalised in the Textpack. Why? Because on the public side only strings of `event="public"` are loaded. So `permlink_mode` is "missing" and is thus passed through the tag verbatim.

By design? Yes.
Confusing? You bet!
Can it be done better? Probably.

**Comment by petecooper** [comment] 2015-07-08 15:54
Can `links` be assigned to `event="public"`, or have I missed something obvious? I know it's used behind the scenes, too - does that make it harder to achieve?

**Comment by philwareham** [comment] 2015-07-08 15:55
This needs to really be given clarification in the tag's documentation. Which is here...

https://github.com/textpattern/textpattern-documentation/blob/master/tag-reference/text.textile

Is it only `public` strings or are `common` strings also loaded - I thought `common` was too but maybe not?

**Comment by petecooper** [comment] 2015-07-08 15:57
It's not a deal breaker, it just looks sloppy where the rest of the theme is on point.

**Comment by Bloke** [comment] 2015-07-08 16:00
Actually yeah, `event="common"` might be loaded too. Easy to verify. If we need to use such strings on both sides, then change its event.

**Comment by petecooper** [comment] 2015-07-08 16:07
Is that something I can do?

**Comment by philwareham** [comment] 2015-07-08 16:13
That is part of it. The other part is for me to change it's type in the RPC server - which I can do once the GitHub repo is amended. Bear in mind that'd mean moving it in each of the Textpacks in the repo - and making sure it falls on the same line number in each of those too.

**Comment by petecooper** [comment] 2015-07-08 16:14
I can do that. Will anything break if this re-org is done prior to you poking the RPC?

**Comment by philwareham** [comment] 2015-07-08 16:25
Nope, the GitHub repo isn't linked to the RPC at all (I wish it was that clever!).

Thanks Pete, appreciated. But please wait for @Bloke to confirm that `common` events are indeed available for public side use.

**Comment by petecooper** [comment] 2015-07-08 16:58
Will do - standing by.

**Comment by petecooper** [comment] 2015-07-08 17:10
Well, I just tweaked the `en-gb` Textpack where I moved `links` to `#@common`, uploaded the Textpack via the admin panel, and I can confirm *it works* - capitalisation works properly, and as expected. Will raise a PR for all languages.

**Comment by Bloke** [comment] 2015-07-08 20:52
Nice one Pete. A good spot.

**Closed** 2015-07-08 21:10 UTC
