### ISSUE TITLE
Front-end website URL

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1344] opened 2018-09-20 16:40 UTC
### Expected behaviour

After a fresh installation, front-end website URL isn't the good one into Preferences.

### Actual behaviour

Front-end website is set as the back-office one into Preferences.

### Steps to reproduce

Fresh installation.

#### Additional information

Currently, a fresh installation of TXP 4.7-dev seems to add the administration link as the front-end website URL into preferences.

Textpattern version: 4.7-dev

**Comment by cara-tm** [comment] 2018-09-23 12:04
The traditional one; from the browser.

**Comment by petecooper** [comment] 2018-09-26 10:53
I cannot reproduce this here - anyone else?

**Comment by NicolasGraph** [comment] 2018-09-26 12:05
> I cannot reproduce this here - anyone else?

Me neither; my site url related pref. value is ok (fresh dev install on Mamp pro).

**Comment by philwareham** [comment] 2018-10-04 08:50
Can't reproduce either. Closing for now. Please re-open if issue becomes more widespread.

**Comment by philwareham** [comment] 2018-12-07 15:43
@bloke @petecooper @bloatware any ideas on this? Looks like server path is being used in the domain section in this MAMP PC setup. I can't verify as I only used Mac MAMP and haven't been able to reproduce (domain is always fine in my installs).

I'm tempted to think this is MAMP not being configured properly, not a Textpattern issue specifically. But if anyone has thoughts then please share.

**Comment by petecooper** [comment] 2018-12-07 15:47
All I can see is a username creation screen grab - was something edited?

**Comment by cara-tm** [comment] 2018-12-07 15:48
I didn't edited the website URL...

**Comment by petecooper** [comment] 2018-12-07 15:48
@cara-tm - thank you for the clarification, my eyes are slow today!

**Comment by Bloke** [comment] 2018-12-07 15:48
Installing MAMP on PC now; will see if I can reproduce this.

**Comment by Bloke** [comment] 2018-12-07 16:17
Does the same for me, good catch, cara-tm!

Weird. Must be something to do with the part that guesses the public URL. Will investigate.

**Comment by Bloke** [comment] 2018-12-07 16:54
Bah, regexes!

```
#^(.*?)(\textpattern)?/setup.*$#i
```

When compared against `/test-site/textpattern/setup/index.php` doesn't match anything and returns the full string.

See the issue?

Yep. Pesky backslash.

The system directory separator is used when constructing `$txpdir`. That resolves to `\` on Windows and `/` on everything else. Then when it comes time to compare the value of `$_SERVER['PHP_SELF']` when we guess the public URL, PHP disambiguates the server and returns it in its canonicalised UNIXy version - using forward slash. We dutifully come along and try to strip out the bit of the path we don't want and... Windows goes "no match" because backslash != forward slash.

I've a tentative patch that works on both systems but I need to make sure we don't use this "trick" elsewhere in setup before I'm happy it's viable.

**Closed** 2018-12-07 17:06 UTC

**Comment by Bloke** [comment] 2018-12-07 17:08
Please clear caches etc and try that. *nix users should not be affected but might be worth a quick test.

Also, if anybody has any multi-site installs on *nix and Windows that they can test this on, it'd be most appreciated.
