### ISSUE TITLE
Hyphen and duplicate article URLs

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1191] opened 2018-03-10 12:52 UTC
For the v4.7 final release.

Please, change hyphen followed by article ID for all duplicate articles by an underscore instead. (e.g. http://mydomain.tdl/my-article_10)

Imagine you have an article url title with a date as suffix (e.g. `03-10-2018-10`). Search engines could missunderstood the last numbers into this kind of URL. Furthermore, adding an underscore before the `#ID`, Google can identifies that last number isn't part of the keywords separated by spaces or its equivalent, hyphens, but a unique identifier (non a part of the words flow).

Note. Lot of actual newspaper websites use that kind of scheme into their URLs.

**Comment by Bloke** [comment] 2018-03-11 16:41
This would probably introduce backwards incompatibility. Doesn't the metadata in the article itself give search engines the info they need? More than just the url would provide at least. That would help them make sense of the url.

**Comment by bloatware** [comment] 2018-03-19 09:50
I actually think that the "duplicate" action shouldn't automatically save the clone, leaving to the user the possibility to first change the title etc, then save the article manually.

**Comment by Bloke** [comment] 2018-03-19 10:07
I kind of agree. That would be inconsistent with other Duplicate actions around the patch (templates, primarily). Is that an issue?

As for mass duplication of articles... dunno. Maybe there's an argument for removing it from multi-edit? Not sure of use cases, we'd maybe need to ask if anyone's used it.

**Comment by bloatware** [comment] 2018-03-19 10:13
We could call it "Copy" rather than "Duplicate" on the Write tab? And leave "Duplicate" (with save) in the widget, in case someone needs it.

**Comment by Bloke** [comment] 2018-03-19 10:22
"Copy" works for me.

So what do you envisage would happen when you click copy?

1. Clear the internal ID.
2. Blank out the article_url.
3. Alter the title somehow to indicate it's a copy (maybe).
4. Indicate somehow (amber flash message?) that it's been copied but not saved yet.

Does this impact plugins / callbacks at all? We'd be going from "has an ID" to "doesn't have an ID" client side, right? Or is it best to introduce a new step for Copy that takes all the current field contents (minus article_url and possibly Title) into a completely new form ready to be saved?

**Comment by bloatware** [comment] 2018-03-19 10:26
That would be `event=edit&step=copy&ID=123`, so article save/publish callbacks are not concerned. Well, we'll find something bw compatible, the question is mainly UX.

**Comment by Bloke** [comment] 2018-03-19 10:29
Cool. Give it a go, see what happens. We've got a 'Copy' string in `[common]` so all's good there.

**Comment by Bloke** [comment] 2018-03-19 10:30
You're intending to pass on the _current_ content in the fields to the clone, right? Not the last-saved' content read from the DB?

**Comment by bloatware** [comment] 2018-03-19 11:03
Good question. I presume, if you have edited and not yet saved an article before copy, you are going to duplicate it? Then our present functionality is right. Hmm...

Actually, the clone is saved as draft, so changing Title (which the author will probably do) changes `url_title` too. Just replace "My Title (5)" with "My Title_5"..? Dunno

**Comment by Bloke** [comment] 2018-03-19 11:14
I think that's why we went with duplicate in the first instance. The logic is:

* If you leave the unique identifier (name, title) the same as it was before clicking Duplicate, append `_copy` (for assets) or the new ID (for articles).
* If you have already changed the unique identifier (name, title) then the Duplicate process uses that name if it can. If not (because it already exists), it appends `_copy`. In the article case it always appends the ID.
* For articles, set publish state to Draft and (I think) clear out the URL title. Because if you're cloning an article you don't wanna publish it immediately.

In all cases, the current field contents is used in your clone. So if you've changed any other fields prior to duplication, they get copied across.

Works well for Page/Form/Style assets. The only annoyance with the current setup in articles is that the URL title will contain the ID. That means you also need to alter the URL title after you've edited the main title, which is not immediately apparent unless you've got the 'meta' twisty in view.

**Comment by bloatware** [comment] 2018-03-19 12:22
URL title is changed on Title change in Draft mode for me. So there should be no problem with `url_title` in a normal workflow. The only thing I would change is create cloned articles `url_title` with `stripSpace()` function, to let plugins transform it as they like via `sanitize_for_url` callback. Currently we just append `-ID` to the parent `url_title`.

**Comment by Bloke** [comment] 2018-03-19 12:36
> URL title is changed on Title change in Draft mode for me

Ah, you're right. But not, it seems, after cloning. Once it has the ID in it, changes to the Title don't seem to be reflected in the URL title. Even if (it appears) I manually edit out the ID. Bug, or by design?

We could try using `stripSpace()` for sure. The only reason for the enforced ID was to bypass the "duplicate article" warning and for atomicity in multi-user environments.

**Comment by bloatware** [comment] 2018-03-19 12:58
Weird, cloned articles `url_title` still reflect Title changes for me, as long as it has not been modified manually.

We'd pass through `stripSpace()` the *ID-enforced* `Title (ID)`. By default, it would be converted to `title-ID` as presently, but a plugin could convert it into `title_ID` if preferred.

**Comment by Bloke** [comment] 2018-03-19 13:01
Cool. Must be because I'd altered it by hand. That makes sense actually.

**Comment by bloatware** [comment] 2018-03-21 15:39
This can be done via plugin now. Close?

**Comment by Bloke** [comment] 2018-03-22 09:59
I'm happy to close it. Does the latest beta meet your needs, @cara-tm ?

**Comment by bloatware** [comment] 2018-03-22 10:53
Hm, actually mass-duplicate has not yet been patched, sorry.

**Comment by bloatware** [comment] 2018-03-22 12:29
Well, it's a workflow question: what do you do with duplicated articles? You certainly don't want to mass-publish them with `ID`s in their titles. So you modify titles one by one, unless a plugin does it in one go (but then it could modify `url_title` too). With the latest commits, when you modify a duplicated article title, its `url_title` should be automatically modified too.

This should suffice, unless the new title already exists (and you get an "identical url titles" warning). But this is a general problem, not bound to the duplication. We could automatically append `_ID` to `url_title` in this case, but it's not needed in `messy` or any other mode based on articles `ID`. Thoughts?

**Comment by bloatware** [comment] 2018-04-04 13:35
If we change `-ID` to `_ID` in `url_title` of duplicated articles, it will be considered as customized and **not** reset when `Title` is modified. IMO the suggested remedy would be worse than disease SEO-wise, so closing.

**Closed by bloatware** 2018-04-04 13:35 UTC
