### ISSUE TITLE
Class 'empty' on write page - comments panel and custom fields panel

### ISSUE THREAD

**Issue by ghost** [textpattern/textpattern#415] opened 2014-10-04 13:01 UTC
_From [p...@designhive.com](https://code.google.com/u/100991452291349786445/) on April 24, 2014 18:45:13_

What steps will reproduce the problem? 1. Turn off comments in preferences, or remove any custom field usage from system.
2. Go to the article write/edit page. What is the expected output? What do you see instead? Currently the <section> tag is still left in place, with a class="empty" applied to it (the CSS property is display: none;). There is no content within this tag - it's just <section></section>.

This breaks document outlining - section tags have to include a heading tag. It's also messy code. The better way to achieve this would be to not render the <section> tags at all in these scenarios - NOT rely on CSS to do it.

_Original issue: http://code.google.com/p/textpattern/issues/detail?id=411_

**Comment by vanmelick** [comment] 2015-08-14 22:10
Copying again, this time with tags intact:

What steps will reproduce the problem?
1. Turn off comments in preferences, or remove any custom field usage from system.
2. Go to the article write/edit page.

What is the expected output? What do you see instead?

Currently the `<section>` tag is still left in place, with a class="empty" applied to it (the CSS property is display: none;). There is no content within this tag - it's just `<section></section>`.

This breaks document outlining - section tags have to include a heading tag. It's also messy code. The better way to achieve this would be to not render the `<section>` tags at all in these scenarios - NOT rely on CSS to do it.

---

I seem to recall that the reason for class="empty" was so that the callback hooks remained in play. Just because someone removes all _core-defined_ custom fields or turns off commenting does not mean that a plugin isn't still attached to the hooks to provide alternative functionality.

When it was all `<div>`s it didn't matter so much, but now it's `<section>`s then things are more complicated. There's probably some way we can put valid markup onto the page from the output of the UI callbacks such that there remains an empty container for plugins to use. Haven't looked at the code closely there for a while.

What would be a valid / your preferred markup structure in these scenarios?

**Comment by Bloke** [comment] 2015-08-15 08:33
You're right that `<section>` tags leave unwelcome markup residue. Since plugins may rely on the hooks, could we revert to `<div>`s in the empty instance? Seems a bit hacky, but might be better than crappy markup. Phil probably has a better view on this than me.

**Comment by philwareham** [comment] 2016-01-06 16:57
Revisiting this, since it's a blocker for v4.6 release.

Regarding comments section: Since the comments pref is turned to 'off' for this to happen, we can assume that no plugin associated with comments are not to be active either, right?

If a plugin is circumventing/ignoring the comments pref to add a different system in, then they should IMO either a) respect the pref properly, or b) render a whole new section for that system.

Regarding custom fields: The HTML rendering of whole section is depending on the `$cfs` variable returning _something_, so having an additional check for that variable to render a `class='empty'` is redundant isn't it? [I've removed in this commit](https://github.com/textpattern/textpattern/commit/a6db5add9a291637972ed1e269b6e11255ea15a1).

**Comment by Bloke** [comment] 2016-03-06 23:25
Closed by 5d64e40dff301a9a1a53e66223b46c76b9f843a9

**Closed by Bloke** 2016-03-06 23:25 UTC
Labels: Bug, Component: admin-side, Priority: medium, Usability
