### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#1089] opened 2018-01-04 16:38 UTC
(all TXP versions, latest test with 4.7-dev)

What is the secret behind a successful pagination creation with TXP?

I never obtained such as proper links through pages...
I done some investigations; if grand_total retrieves the right article counting, '?pg=x' queries are exactly the same as this count and I got blank pages without any articles (i.e. for 4 articles count and an article tag with a limit="4" attribute, '?page' queries went to the fouth page while only the first one displays the results.).

Please Devs test and invesdigate.

**Comment by bloatware** [comment] 2018-01-06 21:35
I'm not sure to understand the issue, but just in case:

- the number of pages is stored in `$thispage['numPages']`; `grand_total` stores the number of *articles*
- the pagination is driven by `pg` URL parameter, not `page`.

Does it help?

**Comment by cara-tm** [comment] 2018-01-07 09:43
Sure. Sorry, corrected.
That's the fact: `?pg=x` query get the number of the `grand_total` despite the `limit` value within the `article` tag and TXP renders blank pages (exceeded results).
In substance: it's not so easy to get paginations within TXP...

**Comment by bloatware** [comment] 2018-10-29 15:34
All I know is its validity state has not changed.

> for 4 articles count and an article tag with a limit="4" attribute, '?page' queries went to the fouth page while only the first one displays the results.

Isn't `pageby` attribute set to a different value, by any chance?

**Comment by philwareham** [comment] 2018-12-03 13:10
Closing because of no further feedback. Please re-open if further discussions required in future.

**Closed by philwareham** 2018-12-03 13:10 UTC

**Comment by cara-tm** [comment] 2018-12-12 08:06
(__only for your interest__)
Okay. I finally found where is located this behaviour: it seems that grand_total is dependant of the number of `<txp:article />` tags into the corresponding page template. So, if there are twice calls of the article tag (for some layout raisons) pagination is corrupted.

**Comment by Bloke** [comment] 2018-12-12 08:55
Hmm. Not sure if that's by design. Sounds buggy to me as I'd expect each article tag to manage its own pagination. Is there anything we need to do about this, @bloatware?

**Comment by bloatware** [comment] 2018-12-12 09:01
I have not changed anything in this area, it has always been the **first** `<txp:article />` tag that sets the pagination data. Changing this could result in bwc issues.

**Comment by Bloke** [comment] 2018-12-12 09:10
Okay, I'd have to experiment here and try to article calls on a page to see the effect. I thought @cara-tm was saying that doubling the number of article calls doubles the grand total or something, but maybe I misread it.

As long as only one of the article tags sets pagination, then we'll live with it. But if introducing a second tag on the same page affects that count, then maybe it needs looking at eventually. Edge case at any rate so it can wait.

**Comment by bloatware** [comment] 2018-12-12 11:35
Reading the code, all pagination data are stored in global `$thispage`. It is populated either by `article`, `file_download_list`, `images` or `linklist`, but **only** if it is not set yet.

@cara-tm could you please post the relevant parts of your code and the expected/obtained results?

**Comment by cara-tm** [comment] 2018-12-13 16:12
@bloatware 

Sure Oleg (sorry for the delay).

Here is a page template that cause a persistant link which points on a blank page (due to a first call to the article tag into the styles):

    <!DOCTYPE html>
    <html>
    <head>
    <meta charset="utf-8">
    <title>Sample Template</title>

    <style>

    /*! Get the first image #ID 1 for the hero background */
    <txp:article limit="1">
    <txp:if_article_image>

    .hero {
        overflow: hidden;
        clear: both;
        height: 0;
        margin-bottom: 1.5em;
        padding-top: 56.25%;
        background-image: url(<txp:image_url id="1" link="0" />);
        background-position: center center;
        background-repeat: no-repeat;
        background-size: cover;
    }

    </txp:if_article_image>
    </txp:article>
    </style>
    </head>

    <body>

    <div class="hero"></div>

    <txp:if_author>

        <div class="hed">
            <h2 class="title">Articles by: <txp:author /></h2>
        </div>

        <txp:article limit="5" sort="Posted desc" />

    <txp:else />

        <txp:article limit="5" sort="Posted desc" />

    </txp:if_author>


    <txp:evaluate wraptag="p" class="paginator">
        <txp:newer rel="prev"><txp:text item="prev" /></txp:newer>
        <txp:older rel="next"><txp:text item="next" /></txp:older>
    </txp:evaluate>


    </body></html>

**Comment by bloatware** [comment] 2018-12-15 22:48
We could probably consider an explicit `pageby="0"` attribute as "don't set up pagination"? Or even reset it if the value is not `0`? I don't think this attribute is widely used.

**Comment by Bloke** [comment] 2018-12-16 09:59
That's a great idea, Oleg! As long as 'unset' `pageby` retains existing behaviour, this seems like a winner to me.

**Comment by bloatware** [comment] 2018-12-16 16:33
ok, now `pageby=""` means "don't paginate" and valueless `pageby` means "repaginate". Other cases behave as before, since they are more [frequent](https://forum.textpattern.io/viewtopic.php?id=38541) than I thought. I have not changed  the behavior of other pagination-aware tags (`linklist`, etc) since they work differently and not paginate by default.

@cara-tm so adding `pageby=""` to the first `<txp:article />` should fix your problem.

**Comment by cara-tm** [comment] 2018-12-17 14:30
Pretty cool. Thank you lot Oleg ;)

**Comment by bloatware** [comment] 2018-12-17 14:49
OT, but if it's for your nice [Simplr](https://github.com/cara-tm/simplr/blob/master/dist/simplr/pages/fb_instant_articles.txp) theme, things like
```
<txp:article_custom section="articles,blog" limit="10" month='<txp:php>
// Restriction for only articles of the year and current month.
echo date("Y-m", time());
</txp:php>' />
```
can be done in pure txp:
```
<txp:article_custom section="articles,blog" limit="10" month="today" time="%Y-%m" />
```

**Comment by cara-tm** [comment] 2018-12-17 14:58
😉
