### ISSUE TITLE
Stale session data used in setup/index.php

### ISSUE THREAD

**Issue by kuopassa** [textpattern/textpattern#548] opened 2015-09-19 14:55 UTC
After installing Textpattern 4.5.7 and viewing in localhost PHP's error log this kind of warning is shown couple times:

[19-Sep-2015 13:31:23 Europe/Paris] PHP Warning:  addcslashes() expects parameter 1 to be string, object given in I:\program-files\wam\www\textpattern-checkout-demo\textpattern\setup\index.php on line 624

**Comment by rwetzlmayr** [comment] 2015-09-22 05:08
I cannot reproduce this here.

My I ask you to help us with some additional information? To gather that information you need to add on line into ``setup/index.php``.

Look for a line which says

```
		// Escape single quotes and backslashes in literal PHP strings
```

and replace it with

```
		var_dump($_SESSION);
		// Escape single quotes and backslashes in literal PHP strings
```

After saving this changes please re-run setup with a fresh installation. 

Watch out for the output at step 2 "Add config file" of the setup procedure. You should find something like that right above the "Creating config.php file" headline:

```
array (size=x)
  'lang' => string 'en-gb' (length=x)
  'ddb' => string 'database' (length=x)
  'duser' => string 'user' (length=x)
  'dpass' => string 'password' (length=x)
  'dhost' => string 'localhost' (length=x)
  'dprefix' => string '' (length=x)
  'siteurl' => string 'localhost' (length=x)
  'dclient_flags' => int 0
  'dbcharset' => string 'utf8' (length=4)
```

Please post your result here after purging sensitive information like database user or password.

**Comment by Bloke** [comment] 2015-09-22 08:15
I've had odd things like this happen during setup but they're not easily repeatable. I think it may even have been that same error message, but I can't remember now.

It seems to sometimes happen on a first run, completely fresh installation so, as Robert suggests, it's probably an empty session. If you run setup again on the same browser, the problem doesn't appear, even if you restart the browser (though I suspect this is because the session may persist for some small time period after shut down. Maybe it'd recur if I waited an hour or so).

I've never got to the bottom of it.

**Comment by kuopassa** [comment] 2015-09-22 13:43
Thanks for instructions. Here's the report. It's got apparently some data from an earlier test I did with @yab_shop@ in another Textpattern installation.

array (size=10)
  'wfcart' => 
    object(__PHP_Incomplete_Class)[1]
      public '__PHP_Incomplete_Class_Name' => string 'wfCart' (length=6)
      public 'total' => float 269.97
      public 'itemcount' => int 2
      public 'items' => 
        array (size=2)
          0 => string '16-0' (length=4)
          1 => string '8-0' (length=3)
      public 'itemprices' => 
        array (size=2)
          '16-0' => string '89.99' (length=5)
          '8-0' => string '89.99' (length=5)
      public 'itemnames' => 
        array (size=8)
          '8-0' => string 'Street' (length=6)
          '9-0' => string 'Voigtlander' (length=11)
          '2-0' => string 'Lake' (length=4)
          '6-0' => string 'Flower' (length=6)
          '4-0' => string 'Moon' (length=4)
          '7-0' => string 'Fog' (length=3)
          '3-0' => string 'Stripe' (length=6)
          '16-0' => string 'Kuja' (length=4)
      public 'itemproperties_1' => 
        array (size=2)
          '16-0' => string '' (length=0)
          '8-0' => string '' (length=0)
      public 'itemproperties_2' => 
        array (size=2)
          '16-0' => string '' (length=0)
          '8-0' => string '' (length=0)
      public 'itemproperties_3' => 
        array (size=2)
          '16-0' => string '' (length=0)
          '8-0' => string '' (length=0)
      public 'itemspecshipping' => 
        array (size=2)
          '16-0' => string '' (length=0)
          '8-0' => string '' (length=0)
      public 'itemqtys' => 
        array (size=2)
          '16-0' => int 2
          '8-0' => string '1' (length=1)
      public 'promocode' => int 0
      public 'promocodes' => 
        array (size=2)
          '16-0' => int 0
          '8-0' => int 0
      public 'itemtxpids' => 
        array (size=2)
          '16-0' => string '16' (length=2)
          '8-0' => string '8' (length=1)
  'lang' => string 'en-gb' (length=5)
  'ddb' => string 'txp457-test' (length=11)
  'duser' => string '***removed*** (length=8)
  'dpass' => string '***removed***' (length=8)
  'dhost' => string '***removed***' (length=9)
  'dprefix' => string 'tx1' (length=3)
  'siteurl' => string 'localhost/txp-457-setup-issue' (length=29)
  'dclient_flags' => int 0
  'dbcharset' => string 'utf8' (length=4)


( ! ) Warning: addcslashes() expects parameter 1 to be string, object given in I:\program-files\wam\www\txp-457-setup-issue\textpattern\setup\index.php on line 625

Call Stack
#	Time	Memory	Function	Location
1	0.0020	556128	{main}( )	..\index.php:0
2	0.0170	1951176	printConfig( )	..\index.php:99
3	0.0410	1982320	setup_config_contents( )	..\index.php:387
4	0.0410	1982880	makeConfig( )	..\index.php:699
5	0.0420	1983296	addcslashes ( )	..\index.php:625

**Comment by Bloke** [comment] 2015-09-22 15:17
OK, well that explains it. If the session contains non-string data from some other earlier tomfoolery in another Txp install, then it'll break the setup routine. Maybe we should whitelist the things that `addcslashes` operates upon, instead of just doing it on the whole session array?

**Comment by rwetzlmayr** [comment] 2015-09-22 15:20
This is still relevant for 4.6, so I think it'd at least be better fixed in master. 
We haven't any field reports besides this issue that it affects lots of users so I feel no need to back-port it to 4.5.7.

**Closed** 2015-09-23 04:32 UTC
