### ISSUE TITLE
search options drop-down and multipicker options malfunctioning in IE11

### ISSUE THREAD

**Issue by jools-r** [textpattern/textpattern#616] opened 2016-01-21 17:11 UTC
In IE 11 in Windows 7, the search options drop-down at the top of the list pages shows as a separate button but the options themselves don't show.

The multi-option chooser at the bottom of the articles list shows correctly in the first tier but the second pop-up doesn't show. If you choose “Change Category1” a dialog box appears with “are you certain?” (n German in this case) instead of the second chooser. Clicking OK clears the category settings for Category1!

**Comment by philwareham** [comment] 2016-01-25 12:01
@bloke @vanmelick @petecooper @rwetzlmayr can any of you confirm this issue, I'm running OSX only here so I don't have access to either Win7 or IE11 right now.

**Comment by petecooper** [comment] 2016-01-25 12:07
I can spin up a W7 VM to test. Will report back by close of business today.

**Comment by petecooper** [comment] 2016-01-25 12:08
@philwareham - assign this to me for now.

**Comment by petecooper** [comment] 2016-01-25 18:19
Hmm. Cannot reproduce. I made a screencast with narration, though. That's compressing now and I'll attach shortly. Should be about 15 mins or so, maybe less.

**Comment by petecooper** [comment] 2016-01-25 18:31
Here we go.
[textpattern-616.mp4.zip](https://github.com/textpattern/textpattern/files/103668/textpattern-616.mp4.zip)

**Comment by jools-r** [comment] 2016-01-25 22:03
I hang my head in shame ;-) You rather conclusively and entertainingly proved me wrong. Thanks for going to such an effort, and I'm sorry for the false alarm. I'm almost glad you discovered something else, so it wasn't wasted time…
However, I did see this myself on a colleague’s windows box but I guess there must be other factors contributing to that too. It's an upgraded previous site with quite a number of entries and in German and we had show details clicked too. I'll check if I can narrow it down. Maybe there’s something else in her browser interacting with it...

**Comment by rwetzlmayr** [comment] 2016-01-26 04:35
Cannot reproduce either.

**Comment by philwareham** [comment] 2016-01-26 09:15
Thanks everyone. Sounds like there is a problem with JavaScript firing on jools-r's system. We use pretty standard jQuery code for the multi-select widget and vanilla jQuery UI for the search widget dropdown, so I'll close this issue for now. If we get more reports of this I will reopen.

**Closed by philwareham** 2016-01-26 09:15 UTC
Labels: Bug, Verification required
