### ISSUE TITLE
Multi-domain installation "Cannot redeclare find_relative_path"

### ISSUE THREAD

**Issue by freshmeat123** [textpattern/textpattern#1774] opened 2022-01-09 08:17 UTC
### Actual behaviour

When i try setup multi-domain setup accordingly official documentation i got this error:
````
$ curl https://admin-blog-1.mydomain.com/setup/index.php
<br />
<b>Fatal error</b>:  Cannot redeclare find_relative_path() (previously declared in /var/www/textpattern-4.8.8-beta.1/sites/blog1/admin/setup/index.php:198) in <b>/var/www/textpattern-4.8.8-beta.1/sites/blog1/admin/setup/index.php</b> on line <b>198</b><br />
````
When i run index.php from console i see that index.php run twice:
````
host:/var/www/textpattern-4.8.8-beta.1/sites/blog1/admin/setup # php index.php
PHP Fatal error:  Cannot redeclare find_relative_path() (previously declared in /var/www/textpattern-4.8.8-beta.1/sites/blog1/admin/setup/index.php:198) in /var/www/textpattern-4.8.8-beta.1/sites/blog1/admin/setup/index.php on line 198

Fatal error: Cannot redeclare find_relative_path() (previously declared in /var/www/textpattern-4.8.8-beta.1/sites/blog1/admin/setup/index.php:198) in /var/www/textpattern-4.8.8-beta.1/sites/blog1/admin/setup/index.php on line 198
````

### Steps to reproduce
````
$ cd textpattern-4.8.8-beta.1
$ cp -r sites/site1 sites/blog1
$ php sites/blog1/admin/setup/index.php
````
#### Additional information

Textpattern version: 4.8.8-beta1 and 4.8.7 release

Web server vendor and version: nginx/php-fpm

Database server vendor and version: mysql80

PHP version: php8.0.13

Operating system: freebsd

**Comment by petecooper** [comment] 2022-01-10 13:24
Paging @jools-r for any insight.

**Comment by petecooper** [comment] 2022-01-20 12:08
@freshmeat123 - what happens if you access the setup routine from a browser instead of the command line?

**Comment by freshmeat123** [comment] 2022-01-20 13:03
Same error.

**Comment by petecooper** [comment] 2022-01-20 13:12
I think this is perhaps due to 1 or more errors in the documentation / setup procedure because we've tested multi-site successfully and cannot yet reproduce your error. I'm going to do some more investigation over the next day or so, but it would definitely be worth checking in with the [troubleshooting forum](https://forum.textpattern.com/viewforum.php?id=67) in the meantime.

**Comment by petecooper** [comment] 2023-12-22 23:54
Closing for now due to age and no feedback - can be taken to the forum if required.

**Closed by petecooper** 2023-12-22 23:54 UTC
Labels: verification required, installation / setup, multisite
