### ISSUE TITLE
Uniformity across notification styles, couple of tweaks

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1114] opened 2018-01-16 15:56 UTC
(This is all cosmetic/presentational, low priority in my opinion – raising it for completeness.)

There's some minor disparity between notifications after create/duplicate/upload actions. Nothing to stop the presses for, but here's what I've spotted:

- [x]  duplicated articles don't have bolded IDs (e.g. 5,6 in the screenshot) or a trailing `.`:

![safariscreensnapz011](https://user-images.githubusercontent.com/226578/34997339-2ba147d8-fad4-11e7-87b4-c8d8f31ac06d.png)

* uploaded image filenames are bold, have one tick per file and do have a trailing `.`:

![safariscreensnapz012](https://user-images.githubusercontent.com/226578/34997378-498bde84-fad4-11e7-9c19-5b08b3266689.png)

Related: I'm guessing the multiple ticks/checks on the notification is because the filename length makes an inline list unwieldy – is that right? I ask because…

- [x] when connecting an existing file, the filename isn't bolded, and multiple files only have a single tick between them, there's no colon as an action/file separator, and there's no trailing `.`:

![safariscreensnapz013](https://user-images.githubusercontent.com/226578/34997478-7e6b8eba-fad4-11e7-82e1-192512aa9362.png)

* uploaded files filenames are bold, do have a trailing `.` and have one tick per file:

![safariscreensnapz014](https://user-images.githubusercontent.com/226578/34997548-b05f9a6a-fad4-11e7-9581-efa6bae20b89.png)

There will likely be some crossover between here and https://github.com/textpattern/textpacks, but I'm raising it here first.

Thanks for reading.

**Comment by Bloke** [comment] 2018-01-16 16:58
Check marks in the flash message area should be consistent, imo. One check per box, not per file/line. It's probably adding each file to the array as a separate message instead of stuffing a single array of them to the flash areas in one go.

**Comment by Bloke** [comment] 2018-01-16 17:02
The lack of bold in duplicated_articles (now called `articles_duplicated` for consistency with other strings) is because it's showing the raw string token, btw. It'll be fixed when https://github.com/textpattern/textpacks/commit/e72cd24a56b28bcb7d22446e11aadec6b6532646 hits core.

**Comment by philwareham** [comment] 2018-01-16 17:07
The string:

    linked_to_file="Linked record to file"

Doesn't have a placeholder for the list within it - somebody needs to fix the core code first - then I can do the following:

    linked_to_file="Linked record to file: <strong>{list}</strong>"

**Comment by philwareham** [comment] 2018-01-16 17:09
Wouldn't the alert boxes be better as, for example:

    Files uploaded: file1.png, file2.png, file3.png

I though that was why we changed the working of text strings? At the moment it's printing the whole line multiple times.

**Comment by Bloke** [comment] 2018-01-16 17:17
Yes, it's supposed to use the `{list}` style strings. This work probably pre-dates the work we did on lang-on-demand so it got missed.

**Comment by phiw13** [comment] 2018-01-16 23:23
> Check marks in the flash message area should be consistent, imo. One check per box, not per file/line. 

Depends… At least for the Files panel, it gives you a warning when you try to upload a file that already is recorded in the DB (and the duplicated file is not uploaded). The Images panel allows one to upload the same image multiple times (would be nice if it gave the same warning as for the Files panel, but that is probably a separate issue).

![screen shot 2018-01-17 at 8 13 57 am](https://user-images.githubusercontent.com/8944809/35017125-e11e80e6-fb5e-11e7-9960-4031c4f4269c.png)

I agree though that a successful upload of multiple files/images should just spit out a list.

**Comment by bloatware** [comment] 2018-01-17 15:29
> Check marks in the flash message area should be consistent, imo. One check per box, not per file/line.

I'm with @phiw13 on that, separate warnings are easier to spot. What if we just remove the "success" icon (or rather make it transparent)? The general status is indicated by the color anyway, and errors/warnings will stand out more clearly.

**Comment by Bloke** [comment] 2018-01-17 15:35
Suits me. I'm happy with whatever makes most sense and doesn't overwhelm the user with masses of unnecessary crufty messaging.

**Comment by bloatware** [comment] 2018-01-17 15:49
For "success" icons, `.ui-icon-check {visibility:hidden}` should suffice. And I will tweak linking existing files message.

**Comment by phiw13** [comment] 2018-01-18 03:11
> For "success" icons, .ui-icon-check {visibility:hidden} should suffice. And I will tweak linking existing files message.

Hmm, make it a bit more generic? This can go in the stylesheet (rather than hardcoding in the `html`):

```
#messagepane .ui-icon ~ .ui-icon { visibility: hidden; }
```

Or do you think it possible to have a situation with `error` message, followed by, a `warning` message and then some `success` message(s) ? And you only want to hide the `success` icon? In that case:
```
#messagepane .ui-icon ~ .ui-icon-check { visibility: hidden; }
```

**Comment by bloatware** [comment] 2018-01-18 12:10
Currently the messages are not grouped by their status (and they shouldn't be, imo). The idea is to display the icons only for errors/warnings, since they require attention. But I leave it with theme authors.

**Comment by philwareham** [comment] 2018-01-18 12:46
Just reading this issue list. So we can potentially have success/warning/error state texts all in the same message pane now, I guess? That kind of breaks the colouring I use for message background to indicate the state so I'll have to rethink this UI.

I don't want to get rid of success ticks in my themes as I have no problem with them - but the message colour probably needs attention. Leave it with me.

The various items not being listed as proper lists I can't personally do, since I don't have the PHP chops to fix that. Someone else will have t take ownership of that issue.

**Comment by Bloke** [comment] 2018-01-18 13:17
Yeah, we do that in Theme importing too. To test:

1. Export a couple of themes to disk.
2. Edit some of file names of _one theme's_ Forms/Pages to include character symbols that we deem illegal in Txp.
3. Re-import the themes from multi-edit.

You'll see that it'll succeed reading one theme overall but will issue a warning for the failed assets in the other. In this case, I think it triggers an orange alert box but the colour is situation dependent and determined in code. So whatever we decide about "combined" error states, we should aim to be consistent.

Perhaps when we move to a slightly more flexible flash message class, we could group them and output a green box with all the success messages in it and an amber box beneath it with the warnings in it? Or we could continue as now - intermingled messages - but instead of the entire box being a single colour, make each "message" its own colour background. If we have a bunch of greens together, they'd still be styled to look like one solid group. The only trick might be to hide (like phiw13 suggests) all icons of the same type that occur in succession so the number of icons isn't overwhelming:

```
 icon-check Did something good
            Did something else good
 icon-warn  Had a problem
 icon-check Did something well
            Did something really well
...
```

**Comment by bloatware** [comment] 2018-01-18 13:18
> So we can potentially have success/warning/error state texts all in the same message pane now, I guess?

Yes, e.g. for multiple files upload: some are uploaded fine, some already exist. The coloring scheme is: all success - green, all errors - red, otherwise yellow(ish).

> The various items not being listed as proper lists I can't personally do, since I don't have the PHP chops to fix that. Someone else will have to take ownership of that issue.

I have already done it, just tweaking before submit.

**Comment by bloatware** [comment] 2018-01-18 13:22
> Perhaps when we move to a slightly more flexible flash message class, we could group them and output a green box with all the success messages in it and an amber box beneath it with the warnings in it?

The problem is that messages can come from many sources now (core, plugins). I'm not sure grouping them by status is optimal.

> make each "message" its own colour background

Isn't that what the icons are for?

**Comment by philwareham** [comment] 2018-01-18 13:39
How's this?

![grab](https://user-images.githubusercontent.com/413665/35100785-f4eb240c-fc54-11e7-8269-c72488584191.png)

**Comment by Bloke** [comment] 2018-01-18 13:39
> I'm not sure grouping them by status is optimal.

Me neither! Just throwing things out to see if it sparks anything better,

> Isn't that what the icons are for?

Yes and no. An "error" icon on an otherwise green background is a confusing message though. I'm guilty of not reading the message and just assuming if I see a flash of green that everything's okay, then hitting escape to close it.

**Comment by bloatware** [comment] 2018-01-18 13:41
> An "error" icon on an otherwise green background is a confusing message though.

Currently, green = all success, it's at least orange otherwise :-)

**Comment by petecooper** [comment] 2018-01-18 13:44
>How's this?

I feel like I'm at an optician and you're going to ask if the text is clearer on the red or green, then flip the 4-way monocle around…

(I kid, looks ace!)

**Comment by Bloke** [comment] 2018-01-18 13:57
> Currently, green = all success, it's at least orange otherwise :-)

That's what I'd hope too! Even if the message collection included some successes, I'd expect the orange or red depending on the severity of the "worst thing that just happened". I just hope it's consistent. I already squashed a couple of corner case bugs from 4.6.2 in some panels where you did an action and it failed with a green background. Hope we haven't introduced any more such cases with multi-message boxes.

**Comment by phiw13** [comment] 2018-01-18 14:09
> Currently, green = all success, it's at least orange otherwise :-)

Yeah, the current state: success - green, otherwise yellow/amber is fine as far as I’m concerned. I can see the point about removing all icons except the first one (a bit of info overload), eventually (*). On the flip side, having the icons there helps seeing the difference between the lines (in my screenshot above, one warning and 2 succeeded).

(*) imagine, a message box with only one icon and the following sequence of actual messages:
- a warning
- a success
- another success
- a warning
- a success

That is quite hard to read. Or maybe it is a positive… forces the user to actually _read_.

**Comment by bloatware** [comment] 2018-01-18 14:20
> How's this?

Portuguese! :-) No, -1

**Comment by Bloke** [comment] 2018-01-18 14:23
> I can see the point about removing all icons except the first one

I was wondering more if we could remove the icon if it occurs multiple times in succession:

* a warning (warn)
* a success (check)
* another success (nothing - same type as previous message)
* a warning (warn)
* a success (check)

Not sure if CSS can do that hide-sibling-except-first-of-this-type thing :-) Nor sure if we'd want to...

**Comment by philwareham** [comment] 2018-01-18 14:23
I'm out then - fix it amongst yourselves. Send me the CSS when you're done.

**Comment by Bloke** [comment] 2018-01-18 14:26
Maybe we stick with what we have for now. As long as the uniform box background behaves as we intended above (only shows the colour of the "worst" error in the set) then we're covered.

I can live with multiple icons or whatever happens. Not a deal breaker for me in any way.

**Comment by philwareham** [comment] 2018-01-25 15:06
This is done now as far as I'm concerned - please test and close the issue if OK.

**Closed** 2018-01-25 15:07 UTC
Labels: Usability
