### ISSUE TITLE
Preview in modal dialog for 4.8?

### ISSUE THREAD

**Issue by bloatware** [textpattern/textpattern#1439] opened 2019-12-06 12:44 UTC
### Is your feature request related to a problem?

Nope

### What is the feature?

Currently clicking article HTML/Preview tabs loads a new page. This yields at least two inconveniences when getting back to Text tab:

- you loose browsers cursor position and undo/redo history
- file type inputs (currently none in core, but added by some plugins) are reset

Should we rather display HTML/Preview in a separate dialogue? Actually, that's already implemented in `custom-fields` branch:

![preview](https://user-images.githubusercontent.com/11578435/70323557-58c32380-182d-11ea-9769-a2fab163891a.png)

As an extra benefice we could get 'live' preview while typing.

**Comment by philwareham** [comment] 2019-12-06 12:50
If this can be done nicely, the definitely yes. The tabs UI in that instance would not make sense anymore - so we'd have to redo that area somewhat (but should be relatively easy to do).

**Comment by Bloke** [comment] 2019-12-06 13:04
Hell yes! Back-port it from custom-fields if you have to and extend it. Take it steady to avoid conflicts with that branch when remerging dev :)

One thing to add to what Phil says: what are we going to do about the callback for the view modes (@article_ui > view@)? Ditch it? Does anyone use it? I think maybe Sacripant did in his [tom_write_editor](https://forum.textpattern.com/viewtopic.php?id=48008) plugin but that's the only one I can think of.

**Comment by bloatware** [comment] 2019-12-06 13:08
@philwareham that's the same UI-dialog we use in tagbuilder, fwiw. I'd leave with you the tabs destiny.

@Bloke needs live testing, as ever :-)

**Comment by petecooper** [comment] 2019-12-06 14:36
Strong +1 from me - great idea.

**Comment by bloatware** [comment] 2019-12-06 15:37
The first pass is done, please test. Once cleaned up (removing direct `Prism` call in `textpattern.js` etc) I'll remerge it into cf.

**Comment by Bloke** [comment] 2019-12-06 16:54
Oooh nice! I'm getting odd JS errors on some articles though, and some bizarre box behaviour and Save sometimes fails, as does 'escape' to dispose of the flash message. Can't pin it down, but I think it might have to do with one of my test articles having a `<script>` tag in it. Although it could be a plugin: I'd have to turn them all off to find out.

**Comment by bloatware** [comment] 2019-12-06 17:05
Yes, `escape` *closes* focused dialogs but *toggles* the flash message, which can produce weird effects. We can make it just *close* the latter too, but then there would be no mean to reopen it until the next event.

What kind of JS errors?

**Comment by Bloke** [comment] 2019-12-06 17:09
```
TypeError: $(...) is null                  textpattern.js:895:30
TypeError: $.type is not a function        textpattern.js:1525:11
TypeError: input.files is undefined        textpattern.js:1017:17
...
```

**Comment by Bloke** [comment] 2019-12-06 17:12
And huh, I never noticed that esc toggled the flash messages. How cool! A number of times I've slapped the escape key too quick without reading the message and wished I could get it back to read it

**Comment by bloatware** [comment] 2019-12-06 17:17
That's strange: `$.type is not a function`. As if `$` were not `jQuery` object.

**Comment by bloatware** [comment] 2019-12-06 17:21
Previewing triggers JS execution, that might be the reason.

**Comment by Bloke** [comment] 2019-12-06 17:22
Yeah. If I take out the `<script>` tag from the body, it previews fine.

**Comment by Bloke** [comment] 2019-12-06 23:43
Latest commits are much better, thank you!

**Comment by bloatware** [comment] 2019-12-07 09:31
@Bloke thanks, I have never spotted these little quirks. Now JS is not executed in preview any more, this makes it more stable and secure.

**Comment by Bloke** [comment] 2019-12-07 09:45
That's what I'm here for. I have an uncanny knack for breaking things if I try hard enough :)

**Comment by bloatware** [comment] 2019-12-07 09:57
I don't even have to try hard :-)

**Comment by phiw13** [comment] 2019-12-08 01:03
With ‘Live Preview’ enabled, seen the following while saving (the article was already saved once, this is the second “save” action).

```
Article not saved. [username] modified the article while you were editing it. If you’re sure, press the ‘Save’ button once more.
```

I had, between the two @save@ actions, switched from text preview to HTML preview. Then I added some more content to the `Body` field.

[username] is me.

Barebones install, only plugin is glz_custom_fields, the article is saved as “draft”, preference setting

**Comment by bloatware** [comment] 2019-12-08 09:59
That happens sporadically and independently of live preview, when you edit an article in two browser tab, for example. Please report if it reproduces itself.

**Comment by cara-tm** [comment] 2019-12-12 09:07
The integration of the new link "Preview" is much better IMHO (today's commit). Maybe you could consider placing the slug URL field ("URL-only title") next to but hidden by defaut: I noticed lot of users want to change this field content because it is available into the right colomn where lot of change possibilities are placed.

**Comment by Bloke** [comment] 2019-12-12 12:25
As of d2ce762d I'm seeing slightly odd behaviour:

1. Edit an article.
2. Open preview.
3. Switch Live Preview on.
4. Edit article. Note live updates occur in dialog.
5. Hit CTRL-S to save the article. Live preview checkbox is cleared.
6. Edit article. Note live updates still occur in dialog.

The checkbox should not be cleared on save, imo. Its state should be preserved in localStorage.

**Comment by bloatware** [comment] 2019-12-12 14:41
@Bloke thanks, should be fixed now.

**Comment by phiw13** [comment] 2019-12-13 12:20
Is there a way to set a class on the top level `div` of the dialog (the one generated by JQ-UI). It already sets a `.ui-dialog` class among many others. It would be nice to be able to target this particular dialog to set `position:fixed` so that the modal  preview always remain in view, no matter how much the user scrolls the page.

I know it can be targeted with the page specific ID (set on the `body`) but I wish for something more specific to the dialog - and who knows in the future, this modal Preview might get reused somewhere els).

PS - the generic `.ui-dialog` used to be set to `position:fixed` but that caused tons ofp issues with the tag-builder on Pages and Forms, due to the twisties toggles - there is a closed issue somewhere in the Hive repo or here.

I am referring to this `div` (generated code) where I’d want an additional class:

```
<div style="position:absolute; height: auto; width: 380px; top: 16.703125px; left: 864px;" tabindex="-1" role="dialog" class="ui-dialog ui-corner-all ui-widget ui-widget-content ui-front ui-draggable ui-resizable" aria-describedby="jquery-ui-dialog" aria-labelledby="ui-id-1">
```

**Comment by bloatware** [comment] 2019-12-13 12:42
Will it be ok if we assign it some `txp-preview` class?

**Comment by phiw13** [comment] 2019-12-13 12:44
Yes sure.

Now I see the tag-builder already has such a class (`.txp-tagbuilder-container`). Perhaps by analogy you could use `.tpx-preview-container`.

**Comment by bloatware** [comment] 2019-12-13 13:10
Ok, [done](https://github.com/textpattern/textpattern/commit/da62f033869899fe073c0c283146c8f255930169).

**Comment by phiw13** [comment] 2019-12-13 13:22
Aah, you put it _inside_ the dialog. I really meant at the top level (the div at the top of the screenshot, starting with a style attribute).

That is where the positioning and the dragging is controlled.

<img width="956" alt="TXP preview" src="https://user-images.githubusercontent.com/8944809/70802985-539a4180-1df6-11ea-9dc7-21b540c7c545.png">

**Comment by phiw13** [comment] 2019-12-13 13:24
I think, for the tag builder, (Pages panel) the class is inserted here: https://github.com/textpattern/textpattern/blob/dev/textpattern/textpattern.js#L2237

**Comment by bloatware** [comment] 2019-12-13 14:01
Ah yes, right, [thanks](https://github.com/textpattern/textpattern/commit/c6270d809ff96815d391b94c4080f56112648f7e).

**Comment by phiw13** [comment] 2019-12-14 01:02
> Ah yes, right, thanks.

Perfect ! thanks.

**Comment by petecooper** [comment] 2019-12-16 19:09
What's the consensus here, as of now? Are we broadly happy this looks and plays as expected?

I've gone over the thread and I can't see anything outstanding.

Thanks, all.

**Comment by philwareham** [comment] 2019-12-16 20:28
I’ve got a couple of changes to make, so please leave issue open for now.

**Comment by philwareham** [comment] 2019-12-17 10:52
OK, I've had a look over the current state of the preview dialog window, and I have the following suggestions you may/may not like to consider:

1. In the tabs, the first tab should ideally be called 'Text' not 'Preview', since we have already clicked a 'preview' link to open the dialog window.
2. Don't really need `title` attributes on these tabs now, it's fairly obvious that these will preview text and preview HTML in this context.
3. For consistency with the rest of the UI, the dialog titlebar should display 'Preview', not the field's name.
4. Related to 3 above, maybe we add a `h2` heading in the dialog window (above the view mode tabs) that states the field's name? Don't know until I see it, but that keeps consistency with the way Help dialogs are displayed.

Visual attached for debate:

<img width="467" alt="Screenshot 2019-12-17 at 10 47 18" src="https://user-images.githubusercontent.com/413665/70989159-0995b200-20bb-11ea-8a80-73ac3ed0a77c.png">

**Comment by Bloke** [comment] 2019-12-17 13:46
All great stuff, Phil. Perfectly logical, functional and lovely to look at.

**Comment by bloatware** [comment] 2019-12-17 15:08
Fine, but I would rather stick the (inverted) tabs to bottom in this case. This leaves the possibility to display multiple fields (like `Body`, `Excerpt`, etc) in a common dialog.

**Comment by phiw13** [comment] 2019-12-18 05:00
@philwareham

Yes, on point one, I had suggested as much upthread or in the forum thread, I forgot. Ditto on point 3.

Not sure on point 4, If more controls are being addd there as Oleg seems to imply, it becomes fairly crowded. although it does make sense for consistency.


-^-^-^-

What is the point of that OK button being added at the bottom ? Just for the sake of closing the dialog ? Isn’t it a bit overkill ? And if you move the tabs to the bottom they’ll take up their own space / row. Soon there will be no space left at all for an actual preview.

**Comment by philwareham** [comment] 2019-12-20 10:35
This is the final open issue blocking 4.8 release as far as I can see. Would be good to get it finalised. I'm still voting for https://github.com/textpattern/textpattern/issues/1439#issuecomment-566489983 as the display. I don't really see much benefit in having a single dialog covering all fields in a common dialog.

I'm off for Christmas vacation after today so I've mopped up all other things I can to get Textpattern 4.8 beta out (apart from one pophelp which I will write today). I'll keep track of any Crowdin translations that are done and merged them in remotely before beta.

Have a good Christmas and New Year, if you celebrate them!

**Comment by bloatware** [comment] 2019-12-20 11:45
It would be much safer (limited testing time-wise) to place the title under the tabs. Or we could CSS-position it to top. I have just updated the code, please check. Replacing `view_preview` string with `view_text` will not work in all languages: the latter is translated as 'Editing' in Russian. I guess you'd have to modify `view_preview[_short]` strings themselves.

**Comment by philwareham** [comment] 2019-12-20 12:56
Hi Oleg, I'd prefer heading above but I can live with it as-is.

OK, so if you can do the following too, I'll be happy:

1. Remove `title` attributes from the tabs.
2. Change the `gTxt('view_preview_short')` on the first tab to `gTxt('text')`.
3. Remove the `gTxt('view_html_short')`one the second tab and hardcode `<bdi dir="ltr">HTML</bdi>` onto that instead (saves one unnecessary translation string).

**Comment by bloatware** [comment] 2019-12-20 14:23
@philwareham quickly done, but there seems to be no `text` string.

**Comment by philwareham** [comment] 2019-12-20 15:01
OK, I have nothing more to add at this time. Happy to close this issue and go to 4.8.0 beta whenever you guys are ready.

**Comment by Bloke** [comment] 2019-12-21 00:40
Just an addendum to what [phiw13 said earlier](https://github.com/textpattern/textpattern/issues/1439#issuecomment-562901830). Are we considering the following as correct behaviour?

1. Create new article.
2. Type a title and some body content.
3. Hit CTRL-S to save. Note: green response.
4. Hit CTRL-S again to save, without making any changes. Note: red response: 'Article not saved. {user} modified the article while you were editing it.' Where {user} is me.

Each successive use of the save function toggles between green/red results.

This behaviour only affects newly-created articles. Compare it to the situation when loading an already-created article:

1. Visit Articles panel.
2. Select the article created above to edit it.
3. Hit CTRL-S to save. Note: green response.
4. Hit CTRL-S again to save, without making any changes. Note: green response, as expected.

**Comment by phiw13** [comment] 2019-12-21 06:12
Thanks for revisiting this. I can confirm your steps, and some details: editing the article after the 1st save, or edit any other field, triggers the same error.

Here is one more puzzling little thing. After the 1st save, the `prev/next` links are _both_ active although the `next` should not be - and it links to the just saved article in front of you itself. After saving a second time that oddity goes away.

**Comment by Bloke** [comment] 2019-12-21 10:09
Didn't notice the next/prev thing. Very odd, good spot.

**Comment by bloatware** [comment] 2019-12-21 10:55
Yep, annoying. Into the code...

**Comment by Bloke** [comment] 2019-12-21 14:46
Looking good, thanks Oleg!

**Closed** 2019-12-21 15:26 UTC
