### ISSUE TITLE
PHP 8.3 linklist with label attribute prevents page loading

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#1890] opened 2023-11-25 08:35 UTC
With the default theme:

- find the “body_aside” form (Misc. type), 
- add to the `txp:linklist` tag: `wraptag="p" label="thisLABEL"`
- load or reload the front page. Watch the browser progress bar (or spinning icon) stop and you wait and you wait. after a long wait, a browser message: server too busy, connection reset (see this in the forum: https://forum.textpattern.com/viewtopic.php?pid=335896#p335896) but no page…

The httpd error log has this (localhost + apache):

> Fatal error: Maximum execution time of 30+2 seconds exceeded (terminated) in /Users/username/Sites/testbed/textpattern/lib/txplib_misc.php on line 1833

This worked fine with the exact same configuration and PHP 8.2.

Note:
It is _possible_ that other TXP tags combined with this `label` attribute exhibit the same problem, but so far I haven’t seen it.

**Comment by jools-r** [comment] 2023-11-25 10:55
Some functions use the [doLabel](https://github.com/textpattern/textpattern/blob/c03acfc359f68bb366e1a12eadbca8896d730ed3/textpattern/lib/txplib_html.php#L1948) function and others leave it to be handled by the tag-wide [txp_wraptag](https://github.com/textpattern/textpattern/blob/c03acfc359f68bb366e1a12eadbca8896d730ed3/textpattern/publish/taghandlers.php#L3524) function. linklist does the latter.

Presumably, one could fix this by modifying [this line](https://github.com/textpattern/textpattern/blob/c03acfc359f68bb366e1a12eadbca8896d730ed3/textpattern/vendors/Textpattern/Tag/Syntax/Link.php#L159) to read:

```
return $out ? ($label ? doLabel($label, $labeltag) : '') . doWrap($out, $wraptag, $break, $class) : '';
```

and adding "labeltag" and "label" as attributes in the [linklist attributes](https://github.com/textpattern/textpattern/blob/c03acfc359f68bb366e1a12eadbca8896d730ed3/textpattern/vendors/Textpattern/Tag/Syntax/Link.php#L38-L54).

But this didn't exist beforehand and works in php 8.1 / txp 4.8.8, so maybe the problem lies with txp_wraptag or the registerAttr attribute handling functionality?

**Comment by bloatware** [comment] 2023-11-25 11:32
Looks like php 8.3 bug for me. As soon as I comment `//unset($txp_atts[$name]);` in `lAtts()` function (l. 1833) and empty global `txp_atts` array instead, things go better. But what is wrong about `unset($txp_atts[$name]);`???

**Comment by jools-r** [comment] 2023-11-26 16:41
Works for me with PHP 8.3 on local homebrew setup. Thank you! 👍

**Comment by Bloke** [comment] 2023-11-26 20:48
Can't see any reason for the change in behaviour in the [PHP 8.3 release notes](https://www.zend.com/blog/php-8-3) or [migration guide](https://www.php.net/manual/en/migration83.php). Weird.

**Comment by phiw13** [comment] 2023-11-26 23:51
This seems to work now, local Homebrew setup with both a default install and the old-old-old testbed&playground. So far I haven’t seen any unexpected side-effects.

**Comment by bloatware** [comment] 2023-11-27 22:30
This looks like a weird internal pointer bug. This worked:
```
<txp:section_list label="sections" labeltag="h2" wraptag="ul" break="li" />
```
but not this:
```
<txp:section_list wraptag="ul" break="li" label="sections" labeltag="h2" />
```
In both cases we are unsetting `$txp_atts` array elements (some of which are referenced), but in a different order. I can not reproduce the issue outside of txp, though.

Pity, now we have to duplicate the array on loops, which is waist of cycles. But there is a chance php 8.3.1 will be released before txp 4.9 ;-)

**Comment by bloatware** [comment] 2023-11-28 22:37
I have narrowed it to a bare minimum. This (ok, weird) code works in php 8.2 but halts in 8.3:
``` php
<?php
$test = array(
  'wraptag' => 'ul',
  'break' => 'li',
  'label' => 'sections',
  'labeltag' => 'h2',
);

unset($test['wraptag']);
unset($test['break']);
//unset($test['label']);
//unset($test['labeltag']);

foreach($test as $k => &$v) {// mind the reference
    foreach($test as $kk => $vv) unset($test[$kk]);
}

unset($v);
var_dump($test); //empty array
```
Amazingly, if we unset only, say,  `$test['break']` before entering the loop, everything is fine. It's fine also if we loop by value `$k => $v`, whatever keys pre-unset. My php-fu is ko.

Don't try on a live php 8.3 server, it could bite.

**Comment by bloatware** [comment] 2023-12-02 10:51
PHP 8.3.0 bug confirmed and fixed. That means that current txp versions are not usable on 8.3.0, but will be again on 8.3.1. Should we adapt (degrade) txp 4.9 core code just for 8.3.0 compatibility? Would be pity...

**Comment by Bloke** [comment] 2023-12-02 11:37
P.S. We should note this in our HISTORY or README.md that Txp will not run on 8.3.0.

**Comment by phiw13** [comment] 2023-12-02 11:45
Nice work  @bloatware !

Of course you should not hurt Textpattern for this.

> Anybody have any intel on when 8.3.1 is expected?

I guess in 3 weeks or so (based on their usual pattern) @petecooper would know for sure.

(don’t worry about my testbed site, this issue is actually easy to work around)

**Comment by petecooper** [comment] 2023-12-02 12:34
> Anybody have any intel on when 8.3.1 is expected?

RC is tagged Dec 5th, GA is tagged Dec 19th.

Assuming no deviation from regular release schedule.

**Comment by petecooper** [comment] 2023-12-02 15:23
Is this our first official PHP bug report that's been triaged and fixed?

**Comment by bloatware** [comment] 2023-12-03 13:47
> Is this our first official PHP bug report that's been triaged and fixed?

Nice to see they have fixed it so quickly.

**Comment by petecooper** [comment] 2023-12-05 16:36
> Anybody have any intel on when 8.3.1 is expected?

8.3.1 RC1 compiled and ready.

**Comment by bloatware** [comment] 2023-12-05 17:10
> 8.3.1 RC1 compiled and ready.

Thanks @petecooper! As soon as it is released, we'll skip 8.3.0 compatibility.

**Comment by petecooper** [comment] 2023-12-05 17:12
ETA: tagged Dec 19 2023, released Dec 21 2023.

**Comment by petecooper** [comment] 2023-12-06 21:21
No sooner had I compiled PHP 8.3.1RC2, I got a note about PHP 8.3.1RC3 being released…so, now I'm compiling PHP 8.3.1RC3.

I can't recall any patch release getting to RC3 before…something's going on at PHP Towers, clearly

**Comment by petecooper** [comment] 2023-12-20 15:54
PHP 8.3.1 compiling now.

**Comment by petecooper** [comment] 2023-12-21 15:38
Paging @bloatware for completeness – is this resolved from your perspective, please?

**Comment by bloatware** [comment] 2023-12-21 15:54
@petecooper not exactly, I haven't yet installed php 8.3.1 :-) Will do in a due course, thanks for the reminder.

**Comment by petecooper** [comment] 2023-12-21 15:56
@bloatware PHP 8.3.1 is installed to `dev-demo` if that saves you some housekeeping.

**Comment by bloatware** [comment] 2023-12-21 17:14
@petecooper yep, and that's great. But I prefer local testing first, before pushing txp changes to the repo.

**Closed** 2023-12-21 21:54 UTC
Labels: bug, tags, php
