### ISSUE TITLE
<txp:hide pass="1">

### ISSUE THREAD

**Issue by makss** [textpattern/textpattern#787] opened 2016-09-29 11:24 UTC
Simple things that make magic. Why no one has done so far is it?

In the first pass are calculated(set) variables, they are displayed or processed in a second pass. I have long been using a similar approach, but with the help of other tools(wrapper based on `ob_start()`).

I bring in one form of content, title, metas, connect additional js and css. During the second pass - all these elements are in the right places page.
If there is a new content type, I simply add another form. All processing of a new type of content placed in one form, I do not need to remember where and what conditions are set to have the right titles, metas, etc.

The example is not entirely intuitive, but...

```
<head>
<txp:variable name="mytitle" value='<txp:site_name />' /> <!-- set default values -->
...

<txp:hide pass="1">
    <title><txp:variable name="mytitle" /></title>
    ...meta_description
    ...meta_keywords
    ...meta_robots
    ...canonical
    ...meta_author
    ...extra include css
</txp:hide>
</head>
<body>
<txp:if_section>
    output section content
    <txp:variable name="mytitle" value="some specific title" />
    set specific meta values, which are displayed in the `<head>` in the secondpass: title,
description, keywords, etc...
</txp:if_section>

Some of the included form...
<txp:if_search>...output content && set metas...</txp:if_search>
<txp:if_individual_article>...output content && set metas...</txp:if_individual_article>

<txp:hide pass="1">
    <txp:variable name="my_extra_js" />
    ...extra include js
</txp:hide>
</body>
</html>
```

**Comment by bloatware** [comment] 2016-09-29 11:51
Nice idea, though not quite new :-)

* [adi_if_content](http://forum.textpattern.com/viewtopic.php?id=46104) plugin can alter the processing order;
* we are considering the introduction of universal `txp` tags attributes, one of them being `txp:order`. It will indicate in which order tags are processed. With them you should be able to do things like this (currently impossible):
```
	<txp:newer txp:order="6">Newer</txp:newer>
	<txp:older txp:order="6">Older</txp:older>
	<txp:article /> <!-- with default txp:order="5" -->
```
This said, `<txp:hide />` tweak is fine for me, but I don't know what are our plans re `secondpass` (Jukka was for removing it).

**Comment by makss** [comment] 2016-09-29 12:31
Yet another way run the tag during the second pass. Same as `adi_if_content insert=""`  (If I get you right.)
```
<txp:variable name="secondpass" value="<txp:title />" />
<txp:variable name="secondpass" />
```


Priorities tag - it's good, but it will complicate Textpattern. In most cases, two passes will suffice.

**Comment by bloatware** [comment] 2016-09-29 12:39
I'm tempted to replace two passes with `re-parse while there are <txp:tags />` (limited to, say, 10 times). Then we could have up to 10 parse orders in `<txp:hide />`. I like it!

**Comment by bloatware** [comment] 2016-09-30 08:33
@Bloke @philwareham @rwetzlmayr @vanmelick is it ok to rely on `secondpass`? I like @makss idea and would even suggest it for 4.6.1, but we must agree on attributes names in case `secondpass` becomes `multipass`. Maybe `<txp:hide reveal="2" />` to trigger processing on the second pass? This leaves the possibility of `reveal="3"` and so on.

**Comment by Bloke** [comment] 2016-10-01 18:48
I'd be tempted to wait a bit. I must admit I don't quite get the example in the OP. Why have code executed inside hidden elements? Isn't that counter-intuitive? I'd probably have to grok it further to see the benefit.

If we're going to do this, I'd rather a dedicated tag for the express purpose of delaying execution or, as you say, remove `secondpass` altogether. Let's face it, the main reason it exists is to make sure that tags that need other things later (such as search counts) can work properly. Having to put such things first _is_ a minor annoyance in some layouts, so if that could be designed out somehow while retaining the parser speed, then I'd be all for that instead of complicating the syntax for a fringe benefit.

I'm definitely interested in the global attributes though if we can figure out a good system.

**Comment by bloatware** [comment] 2016-10-01 19:52
> Why have code executed inside hidden elements? Isn't that counter-intuitive?

If I get it right, the code inside `<txp:hide />` wouldn't be parsed on the first pass, but only on the second one, when all necessary stuff (pagination, etc) is already set. So this would work fine:
```
<txp:hide pass="1">
<!-- will be parsed on the second pass, with pagination data set by txp:article -->
    <txp:newer>Newer</txp:newer>
    <txp:older>Older</txp:older>
</txp:hide>
<txp:article />
```
Of course, this is already possible with the [variable trick](https://github.com/textpattern/textpattern/issues/787#issuecomment-250452528) (or `pgonly` attribute), but enhancing `<txp:hide />` this way seems logical.

> Having to put such things first is a minor annoyance in some layouts, so if that could be designed out somehow while retaining the parser speed, then I'd be all for that ... I'm definitely interested in the global attributes though if we can figure out a good system.

I'm thinking of assigning core tags some default parse order, so `<txp:article />` would be parsed before `<txp:newer />`, whatever their position in the code. This order would be modifiable with some global attribute if necessary.

**Comment by vanmelick** [comment] 2016-10-02 20:39
On 30/09/16 10:33, etc wrote:
>
> @Bloke <https://github.com/Bloke> @philwareham 
> <https://github.com/philwareham> @rwetzlmayr 
> <https://github.com/rwetzlmayr> @vanmelick 
> <https://github.com/vanmelick> is it ok to rely on |secondpass|? I 
> like @makss <https://github.com/makss> idea and would even suggest it 
> for 4.6.1, but we must agree on attributes names in case |secondpass| 
> becomes |multipass|. Maybe |<txp:hide reveal="2" />| to trigger 
> processing on the second pass? This leaves the possibility of 
> |reveal="3"| and so on.
>

I've always considered secondpass something that we should aim to 
remove, doing it all in a single pass.
Whatever is decided, such a change does not belong in a 4.6.x release. 
It's not a bugfix.

--Ruud

**Comment by bloatware** [comment] 2016-10-03 07:48
I saw few examples in the forum suggesting that some sites are using `secondpass`, and don't see how to remove it in a bwc way. And agree re postponing new features to 4.7+.

**Comment by makss** [comment] 2016-10-03 18:41
> Why have code executed inside hidden elements? Isn't that counter-intuitive?

It does not execute the code.
`<txp:hide pass="1">` - Hide code from the first pass.
I think it looks logical.

I do not understand why there was a desire to remove the `secondpass`?
Removing the second passage leads to the appearance of several smaller sub passages. Or will lead to nonoptimal decisions such as `pgonly`.

As I understand it, unfortunately, no one understood my example from the first post.  ;-(

**Comment by bloatware** [comment] 2016-10-03 20:32
@makss Frankly, we understand you idea (I've taken a look at the code to be sure), and I find it nice and natural. But we are discussing the best way to implement it, because once a new attribute is introduced and adopted, it's difficult to go back. As @vanmelick says, it's not a bugfix, so not for 4.6 anyway, but could be a handy feature in 4.7. Just my opinion.

**Comment by makss** [comment] 2016-10-04 04:45
@bloatware,  No problem, the main thing that the next version came out faster than four years.  ;-)
```
v4.5.0    27.08.2012
v4.6.0    10.09.2016
```

**Comment by bloatware** [comment] 2016-10-17 13:25
I have started to work on "automatic" re-processing in [this branch](https://github.com/textpattern/textpattern/tree/bloatware-thispage). It's not yet in a final shape, but things like this work without `pgonly` or any other trick:
```
<txp:newer>Newer</txp:newer>
<txp:older>Older</txp:older>
<txp:article />
```
It's still based on the `secondpass` and gives tags the possibility to be re-parsed if some of their data is missing on the first pass. But `<txp:hide />` trick could still be handy for manual adjustments.

**Comment by bloatware** [comment] 2016-11-13 20:42
Few things have changed since the last comment. Presently, there are two options, as I see it:

* add a specific "pass" attribute to `<txp:evaluate />` (rather than `<txp:hide />`) tag
* or introduce a general core "pass" attribute available to all tags.

I don't really know which solution is better, but we have yet time before 4.7.

**Comment by bloatware** [comment] 2017-06-29 11:16
The initial idea is implemented as `<txp:hide process="2" />` introduced by [this commit](https://github.com/textpattern/textpattern/commit/f2fa924edab5fbeaabfba94412cba668199a853a), please discuss.

**Comment by bloatware** [comment] 2017-07-05 12:20
Now extended to all tags: `<txp:tag process="2" />` acts as `<txp:hide process="2"><txp:tag /></txp:hide>` (processing on the second pass). Closing?

**Closed** 2017-07-09 20:51 UTC
