### ISSUE TITLE
PHP 7.3.0: compact() issues an E_NOTICE level error if a given string refers to an unset variable.

### ISSUE THREAD

**Issue by rwetzlmayr** [textpattern/textpattern#1412] opened 2019-07-09 05:46 UTC
### Expected behaviour

No PHP notices in Txp core.

### Actual behaviour

Txp uses `compact` at various occasions while it does not assert that the compacted variables actually exist. Since PHP 7.3 [`compact` issues an E_NOTICE level error if a given string refers to an unset variable](https://www.php.net/manual/en/function.compact.php).

### Steps to reproduce

- Switch to `Debugging` production status
- Go to the **Sections** panel
- Edit the `Default` section and save it unaltered
- A few PHP notices complaining about unknown variables show up. `adminErrorHandler()` ist triggered.

#### Additional information

This unwanted behaviour might also occur at other code paths I haven't checked.

Textpattern version: 4.8-dev

**Comment by petecooper** [comment] 2019-08-08 16:23
Confirmed with 4.7.3 on PHP 7.3.8:

![Screen Shot 2019-08-08 at 17 20 05](https://user-images.githubusercontent.com/226578/62720060-24676400-ba01-11e9-914b-7f2e1dc73139.png)
![Screen Shot 2019-08-08 at 17 20 11](https://user-images.githubusercontent.com/226578/62720061-24676400-ba01-11e9-979b-d2a0f6305637.png)
![Screen Shot 2019-08-08 at 17 20 15](https://user-images.githubusercontent.com/226578/62720063-24676400-ba01-11e9-86bc-3dee37f931c3.png)
![Screen Shot 2019-08-08 at 17 20 19](https://user-images.githubusercontent.com/226578/62720064-24fffa80-ba01-11e9-971a-d88eb8c3275a.png)

**Comment by Bloke** [comment] 2019-08-08 16:56
Yeah, we shouldn't be using uninitialized variables _anywhere_ as it's bad form. Leave this with me and I'll weed them out.

**Comment by jools-r** [comment] 2019-08-28 21:25
Found another instance when saving an image with smd_thumbnail but the error refers to txplib_misc.php where there's an instance of compact.

`Notice "compact(): Undefined variable: txpuser"
in /Users/julian/Sites/ludewig_2018/textpattern/lib/txplib_misc.php at line 967.`

txpuser is not explicitly defined in the function, but author is as $txp_user.

**Comment by petecooper** [comment] 2019-09-03 11:39
Mentions of `current()` in current code: https://github.com/textpattern/textpattern/search?q=compact%28%29&unscoped_q=compact%28%29

**Comment by Bloke** [comment] 2019-09-26 11:07
I'm confused about the role of the callback params in the calls to `update_last_mod()` in txp_file.php's `file_insert()` and `file_create()` functions.

In the `compact()` we're passing the list of IDs created/inserted, the category into which the files are being stored, and then - from what I can tell of the code - passing the `description` and `title`.

So let's see:

1. file_insert occurs when one (or more) new files are uploaded into a nominated category via the Upload button.
1. file_create occurs when one file in the `/files` dir is selected and added to the database via the Create button.

In both cases, no `description` or `title` are captured - these two fields are only present when doing `file_edit()` or `file_replace()`, although there _could_ be a `title` if passed in via the GET/POST as an array of `titles` (somehow - not sure where this occurs... JavaScript?)

So unless there's some magic going on in `fileshandler()` I can't see how these variables are ever going to be populated with anything. They'll always be empty, right? Only `ids` and `category` are populated.

Similar experience in `file_create()`. Are they included for some future need?

Regarding this particular issue on `compact()` notices, if I'm reading the code correctly, it seems there's a chance - through error in file upload, perhaps all files are too big - that `$title` is _not set_ and therefore will trigger the warning mentioned in this issue on PHP 7.3+ when the `compact()` is encountered?

Am I missing something? Should we initialise `$title` outside the loop? Or do we even need to `compact()` it and `description` at all?

**Comment by bloatware** [comment] 2019-09-26 13:41
I'd need to check, but iirc these fields were already present in pre-4.6 single file upload mode, though unused. It even seems to me that async sending them on upload is already possible in 4.7, we just lack a UI. For test purposes, I have introduced a basic templating "language" in `textpattern.js`, but we'd better use some well-established library. Meanwhile, some initialization is necessary, I guess. Crazy that PHP 7.3 `compact()` is so bwc-breaking.

**Comment by Bloke** [comment] 2019-09-26 13:55
Yeah I figured they were already there as legacy code. Just trying to work out why they're still there (i.e. do they serve any purpose?) and whether we need them or can use them in future somehow. In order to close this issue we probably only need to patch that use of the possibly uninitialized `title` but I thought while we're looking at this, we might as well see what else we're passing along in the `compact()` statements. This file is the only anomaly I could find.

**Comment by bloatware** [comment] 2019-09-26 14:04
One could fill `title`s on file upload if we had an interface. Actually, [Sandspace](https://forum.textpattern.com/viewtopic.php?id=31851) theme probably provides one, I don't remember.

**Comment by Bloke** [comment] 2019-09-26 15:19
We could fill a lot of fields on file upload if we had an interface. The question is: what interface works? Some sort of grid with one file per row? Great for desktop... not for mobile. Hmm.

Alternatively, we could pre-fill the `title` the same as the `filename` on upload only? Perhaps minus the file extension and maybe removing underscores or something? Like a reverse dumb-downer:

1. my_powerpoint_presentation.pptx => my powerpoint presentation
1. Some-File(1)_2019-09-25_v1.txt => Some-File(1) 2019-09-25 v1
1. ...

 Does that make sense or is it better to leave the `title` empty like we do now?

Probably best to split this off into a separate issue. We need one to discuss changes to the Files panel anyway. See [this post](https://forum.textpattern.com/viewtopic.php?id=48313) - but essentially I'd like to borrow some of the neat features from adi_file_tab and put them in core.

**Comment by bloatware** [comment] 2019-09-27 07:54
Sending only *common* file data (e.g. category) on upload would simplify JS-treatment, because we need to reserve some space for each *individual* field when posting. This makes chunks size calculations for big (over php limits) files upload cumbersome. So I'm for your alternative suggestion, but yes, it's a separate issue.

**Comment by bloatware** [comment] 2019-12-04 22:18
The OP issue looks solved now?

**Comment by Bloke** [comment] 2019-12-05 00:47
Yes I think we found all of them. Before closing this, we should capture a separate issue and tag it with 4.9 about the file name dumb-upper, perhaps in combination with general improvements to file handling such as [replacing files](https://forum.textpattern.com/viewtopic.php?id=48313) among other things borrowed from adi_file_tab. Long overdue.

**Comment by petecooper** [comment] 2019-12-18 11:16
>Before closing this, we should capture a separate issue […]

Welcome aboard https://github.com/textpattern/textpattern/issues/1447

I'll close this since OP is fixed, please butcher 1447 as you see fit.

**Closed by petecooper** 2019-12-18 11:16 UTC
Labels: core
