### ISSUE TITLE
article_custom behaviours

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#870] opened 2017-01-03 08:55 UTC
TXP 4.7.0-dev latest. Using a page template with only a `<txp:article_custom />` tag in it.

Case 1°. Works fine:

    <txp:article_custom section="articles" limit="9999" month='<txp:php>
    echo date( 'Y-m-d', time() );
    </txp:php>' status="live" form="my-form" />

Case 2°. Don't work:

    <txp:article_custom section="articles" limit="9999" month='<txp:php>
    echo date( 'Y-m-d', time() );
    </txp:php>' status="live">
            (content of "my-form")
    </txp:article_custom>

Case 3°.  Works fine:

    <txp:variable name="current" value='<txp:php>echo date( 'Y-m-d', time() );</txp:php>' />
    <txp:article_custom section="articles" limit="9999" month='<txp:variable name="current" />' status="live">
            (content of "my-form") 
    </txp:article_custom>

Why do the second case not work? What differencies?

**Comment by makss** [comment] 2017-01-03 09:58
@cara-tm  Use the correct quotes.  `echo date( "Y-m-d", time() );`
===
<txp:article_custom section="articles" limit="9999" month='<txp:php>
echo date( "Y-m-d", time() );
</txp:php>' status="live">
        (content of the "my-form" above)
</txp:article_custom>
===

IMHO, such questions are best asked at the forum.

**Comment by cara-tm** [comment] 2017-01-03 10:04
Ok.
Yes you're right (such question are best asked at the forum).
I apologize.

**Comment by bloatware** [comment] 2017-01-03 10:05
If everything works as intended, this should do too, please test:
```
<txp:article_custom section="articles" limit="9999" month="today" status="live">
        (content of the "my-form" above)
</txp:article_custom>
```

**Comment by makss** [comment] 2017-01-03 11:09
btw, it works too   ;-D
PHP 5.5.35
```
<txp:article_custom section="articles" limit="9999" month="today" time="+1 day, +3 mouse">
        (content of the "my-form" above)
</txp:article_custom>
```

**Comment by cara-tm** [comment] 2017-01-04 06:23
:D

**Comment by philwareham** [comment] 2017-01-04 09:05
Can this be closed, or is there a definite issue?

**Comment by bloatware** [comment] 2017-01-04 16:51
To resume, all cases in OP are bad-formed (quotes...), but two of them are "repaired" on second parser pass. Since the parser promptly complains in debug mode, I wouldn't call this an issue. We can not fix all user errors anyway.

**Comment by philwareham** [comment] 2017-01-04 16:56
Closing. Non-issue.

**Closed by philwareham** 2017-01-04 16:56 UTC

**Comment by cara-tm** [comment] 2017-01-07 07:25
@bloatware: 

I'm sorry Oleg but it seems that the attribute `month="today"` for the `<txp:article_custom />` tag don't work. I can't get the today's published articles, only (but if I set manually the current date into this attribute, it works as expected).
Please, could you try and confirm?

**Comment by bloatware** [comment] 2017-01-07 11:31
> Please, could you try and confirm?

I _know_ it does not work :-) For `month` different from `YYYY-mm-...` format, you need to set `time` too:
```
<txp:article_custom month="today" time="+1 day" />
```
Your snippet is ok too, but requires `php` privileges.

**Comment by bloatware** [comment] 2017-01-08 12:42
Now you can also retrieve today's articles with
```
<txp:article_custom time="%Y-%m-%d" />
```
Or the last month articles with
```
<txp:article_custom month="-1 month" time="%Y-%m" />
```

**Comment by cara-tm** [comment] 2017-01-17 10:07
Thank you lot ;)
https://github.com/cara-tm/RSS-Sitemap-for-Textpattern-CMS/commit/34270480f948c8cac5d6a60528c9e16cc6a694c1
