### ISSUE TITLE
Ending slashes into some URLs

### ISSUE THREAD

**Issue by cara-tm** [textpattern/textpattern#843] opened 2016-11-11 19:05 UTC
Depending of the preferences choice, if this individual article's URL `http://www.my-domain.com/articles/welcome-to-your-site` is a canonical style (without an ending slash), it seems that `http://www.my-domain.com/category/hope-for-the-future/` and `http://www.my-domain.com/category/hope-for-the-future` are two different pages and considered as possible duplicate content by Google bots.

Please, remove these ending slashes from the tag builder (and generaly all link makers too).

i.e. from the `/textpattern/publish/taghandlers.php` file, into the `category()` function:

`$href = substr(pagelinkurl(array('s' => $section, 'c' => $category, 'context' => $type)), 0, -1);`

**Comment by bloatware** [comment] 2016-11-18 09:34
Should be fixed by [https://github.com/textpattern/textpattern/commit/f9118bd13638bbe411589efa7a8d5bcedd953f8e](https://github.com/textpattern/textpattern/commit/f9118bd13638bbe411589efa7a8d5bcedd953f8e).

**Comment by philwareham** [comment] 2016-11-18 09:36
@cara-tm please can you verify all works as intended and we can then close the issue - thanks!

**Comment by bloatware** [comment] 2016-11-18 09:59
I guess we also need to add a .htaccess rule to redirect `some/url/` to `some/url`, like
```
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)/$ /$1 [L,R=301]
```

**Comment by philwareham** [comment] 2016-11-18 10:21
@bloatware is that htaccess rule necessary? As long as the core is putting out all URLs without a trailing slash I think that is enough. It's up to users to decide how they configure their URL handling per domain.

**Comment by bloatware** [comment] 2016-11-18 10:26
@philwareham I agree for new 4.7 sites, but older sites will have their links switched from `some/url/` to `some/url` on upgrade. Not sure what are SEO implications here, neither if this rule helps... not my domain.

**Comment by philwareham** [comment] 2016-11-18 10:37
@bloatware true, but they should still be able to reach the page with a trailing slash regardless of how Textpattern 4.7 outputs URLs, if their server/domain is set to do that. As long as any canonical tags in pages match the URL that Textpattern outputs then wouldn't search engines gradually filter out the duplicate content in favour of the single (non-trailing-slash) content versions?

I'm just a bit apprehensive about assuming users want a strict htaccess rule that 301 redirects all their content regardless of whether it's Textpattern-generated or not.

**Comment by bloatware** [comment] 2016-11-18 11:19
@philwareham That's true, and I readily leave with you all seo stuff :-)

**Comment by cara-tm** [comment] 2016-11-18 12:29
Tested and all works perfectly.
We'll never have duplicate content, now ;)

@philwareham: It seems we don't need this (https://github.com/textpattern/textpattern/commit/6b38ff3c6e473e56f12d2731fc30453f91072874) and you can revert it.

**Comment by philwareham** [comment] 2016-11-18 12:33
@cara-tm technically we shouldn't need it, but it seems some search crawlers are not respecting the HTTP header rules and can index error pages. The addtional meta tag should help prevent that.

**Comment by philwareham** [comment] 2016-11-18 12:34
Closing. Thanks everyone.

**Comment by cara-tm** [comment] 2016-11-18 13:40
`<txp:site_url />` tag keeps a trailing slash.

**Comment by bloatware** [comment] 2016-11-18 14:18
I've left `<txp:site_url />` as is, because many people use it in constructions like `<txp:site_url /><txp:variable name="my_path" />`, that would be broken without the trailing slash.

**Comment by philwareham** [comment] 2016-11-18 14:19
Agreed, I do that on my sites. Re-closing.

**Closed by philwareham** 2016-11-18 14:19 UTC
Labels: Bug

**Comment by cara-tm** [comment] 2018-12-22 19:51
For any interest, here is what the "Nibblers" online tool (http://nibbler.silktide.com/) informe to me with the use of the latest 4.7.2 version:

<img width="538" alt="slash" src="https://user-images.githubusercontent.com/61045/50378143-16f49980-062b-11e9-9fb9-242984d6cb10.png">

(I changed manually some links into the website in order to reduce the double content pages.)

**Comment by bloatware** [comment] 2018-12-22 23:10
There is a hidden `$prefs['no_trailing_slash']` preference that you can enable via a plugin to remove trailing slashes from list links.

**Comment by cara-tm** [comment] 2018-12-23 08:57
Some hidden things... 😲
But it seems that best practice is to use ending slashes everywhere. 😏

**Comment by bloatware** [comment] 2019-01-02 17:41
A less "negative" name (`trailing_slash`?) would be preferable, perhaps? Or even a multi-choice pref (no slash at all, slash only for lists, slash everywhere)? This actually looks like custom URL stuff for me, if we implement it some day.

**Comment by Bloke** [comment] 2019-01-02 20:03
Yes, I'd vote to leave this for a custom URL implementation rather than a binary switch or 'advanced' selection.
