### ISSUE TITLE
Users with staff privileges offered blank Prefs page

### ISSUE THREAD

**Issue by gomedia-adi** [textpattern/textpattern#720] opened 2016-07-02 04:10 UTC
In 4.5, a user with "Staff Writer" privileges was only offered, by default, one option in the Admin menu: Users.

In 4.6, that same user is now offered a Preferences menu item as well.  When this is clicked, user presented with a blank page that says "no_preferences".

Haven't tested other user privileges.

**Comment by bloatware** [comment] 2016-07-03 18:20
I guess, it's a missing translation string problem. Theoretically, any user can access some preferences if authorized (say, buy a plugin):

```
add_privs('prefs.abc_test','1,2,3,4,5,6');
set_pref('abc_test', 'something', 'abc_test', PREF_PLUGIN);
```

**Comment by Bloke** [comment] 2016-07-03 21:45
Yes, Preferences has been opened to all user groups up so that plugins can have more freedom, rather than being restricted to the two groups beforehand. I guess a side-effect of this is that the menu item appears for all users even if there aren't any prefs to see. Hmmm. Not sure how to get round this. Anyone?

**Comment by bloatware** [comment] 2016-07-09 11:45
A fast (but not very reliable) way would be to check `if (has_privs($key))` for some `$txp_permissions` key starting with `prefs.` when constructing the `Admin` tab. Not tested, just an idea.

**Comment by bloatware** [comment] 2016-07-30 10:46
Please test [this branch](https://github.com/textpattern/textpattern/tree/bloatware-patch-1)

**Comment by gomedia-adi** [comment] 2016-08-02 03:41
Looks good to me!

**Comment by bloatware** [comment] 2016-08-02 16:08
This will work for the core, but plugins will be able to add visible preferences only on load, not via admin side callbacks (too late). That's not really restrictive, but may cause bw compatibility problems.

**Comment by Bloke** [comment] 2016-08-10 08:35
Haven't tested this branch yet (sorry) but the backwards compatibility issue worries me slightly. I'll try and test it with a few plugins such as smd_article_stats, which uses a callback to initialise the prefs on first visit to the preferences panel.

Does this proposed patch work reliably for plugins in the cache directory? Any potential issues there?

**Comment by bloatware** [comment] 2016-09-12 11:32
I think the patch #739 works, but am not sure the issue is worth complicating the code manageability. Would drop it if nobody cares.

**Comment by Bloke** [comment] 2016-09-12 12:28
It works for the Prefs, but probably doesn't scale well if we want to roll it out elsewhere.

Thinking about it again, I'd be more inclined to leave the menu intact and just display 'No prefs available' or similar message directly from the `txp_prefs.php` code if there are no prefs to see when you visit the panel.

**Comment by bloatware** [comment] 2016-09-26 11:52
No, it does not scale. Since `no_preferences` string is there now, I close the issue.

**Closed by bloatware** 2016-09-26 11:52 UTC
