### ISSUE TITLE
Write panel: apostrophe encoding weirdness

### ISSUE THREAD

**Issue by Bloke** [textpattern/textpattern#672] opened 2016-04-13 15:23 UTC
On a stock 4.6-dev, create a new article with the following content:

* Title: `I'm an article`
* Body: `I'm the body`
* Excerpt: `I'm the excerpt`
* Meta description: `I'm the description`
* Keywords: `I'm, some, keywords`
* custom1: `I'm a custom field` 

Publish it and note:

* Title rendered as: `I&#39;m an article`
* Description rendered as: `I\'m the description`

Other fields are unaffected and render correctly.

Save article again and note:

* Title rendered correctly: `I'm an article`
* Description rendered as: `I\\\'m the description`

Subsequent saves double the number of backslashes in the description, but the article title remains okay.

Refresh the page / reload the article and the Title reverts to `I&#39;m an article`.

Description fields on other panels function correctly.

**Comment by Bloke** [comment] 2016-04-14 12:07
Can anyone confirm the above on their own installation? Might just be me.

**Comment by phiw13** [comment] 2016-04-14 12:25
I see that as well when I use the ' (U+0027). I never noticed as I always use ’ (U+2019). The latter works fine

**Comment by rwetzlmayr** [comment] 2016-04-14 12:52
That's escapism at work. 

First escape done by [escapetitle here](https://github.com/textpattern/textpattern/blob/750c6c6da63832cb0329542b002f461398cca818/textpattern/include/txp_article.php#L1565). 

Second escape is done by the first appearance of [txpspecialchars via join_atts here](https://github.com/textpattern/textpattern/blob/180c2c3f965271307d3c5502233f8a3cc43170e8/textpattern/lib/txplib_forms.php#L266). 

Third escape is done by the second appearance of [txpspecialchars via join_atts here](https://github.com/textpattern/textpattern/blob/8a43c9697199cef19015fc0e9fe3bef4bf0be364/textpattern/lib/txplib_html.php#L975). 

That's at least one too many, I don't know which.

**Comment by bloatware** [comment] 2016-04-15 09:54
Setting `$double_encode = false` in `txpspecialchars()` seems to help with `Title` (and logical overall). Any downsides?

**Comment by bloatware** [comment] 2016-04-15 10:32
And `$description` is doSlashed twice in `txp_article.php`.

**Comment by bloatware** [comment] 2016-04-19 12:51
There is an additional lonely `&` escape [here](https://github.com/textpattern/textpattern/blob/master/textpattern/include/txp_article.php#L1476). I can fix it some way, but need to know if there is any reason to escape Title differently than, say, Keywords?

**Comment by rwetzlmayr** [comment] 2016-04-19 13:27
I vaguely remember that there is a reason to escape title differently than, say, keywords: When the title is used in the RSS and Atom feeds it has to adhere to [XML syntax](https://www.w3.org/TR/xml/#syntax) which is accomplished by `escape_title`:

> The ampersand character (&) and the left angle bracket (<) MUST NOT appear in their literal form, except when used as markup delimiters, or within a comment, a processing instruction, or a CDATA section. If they are needed elsewhere, they MUST be escaped using either numeric character references or the strings " &amp; " and " &lt; " respectively. The right angle bracket (>) may be represented using the string " &gt; ", and MUST, for compatibility, be escaped using either " &gt; " or a character reference when it appears in the string " ]]> " in content, when that string is not marking the end of a CDATA section.

This does not obviously apply to the title as it is used on write tab. But it might be a hint for further investigation.

**Comment by bloatware** [comment] 2016-04-19 13:35
Thanks Robert. Then why not delegate `&` encoding to `escape_title()`?

**Comment by rwetzlmayr** [comment] 2016-04-19 13:54
I do not know any more. This is all part of our cargo-cult ;)

`git blame` says that @philwareham introduced the first of the triple escapes in https://github.com/textpattern/textpattern/commit/8b84b48fe57a5591f24b6d29856e3c285f618b44#diff-31d4ab425590b4cf04356c6e52ffec11R1461.

The second escape instance was introduced by @bloatware in https://github.com/textpattern/textpattern/commit/242ada44e15d4a1b3db3d20a1384832e168ce990#diff-0b3cef3dffcc8a9774dfa6d412340b4aR5207.

You both might shed more light on the background of your individual reasons to escape or agree on the proper location of escaping.

**Comment by philwareham** [comment] 2016-04-19 14:05
As far as I know I didn't introduce anything different, my panel rewrites involved moving the original values exactly as they were, the surrounding HTML structure was what I was aiming to change.

If I have unknowingly changed the escaping of some value then by all means please correct it.

**Comment by Bloke** [comment] 2016-04-19 14:25
> As far as I know I didn't introduce anything different

I didn't spot this at commit time, but `fInput()` escapes its `value` attribute, while the original code that rendered the widget by hand already escaped it.

Swapping things out for standard functions is fine in principle as long as this type of thing is borne in mind. The trouble is, this behaviour is not immediately obvious from the code because it hands off to `join_atts()` which is where the escaping is actually done.

So we can either `escape_title()` or use `fInput()` or fix `join_atts()`. They all have their upsides and downsides, but I guess as long as there's a note added to the code as to the reason why one is used over the other, it'll help limit recurrence of such double encoding in future.

**Comment by bloatware** [comment] 2016-04-19 14:27
I don't think I have introduced a new escaping neither, only split the [existing one](https://github.com/textpattern/textpattern/commit/242ada44e15d4a1b3db3d20a1384832e168ce990#diff-0b3cef3dffcc8a9774dfa6d412340b4aL5214). We'll have to trace back to 4.5.7 where it worked...

**Comment by bloatware** [comment] 2016-04-19 14:30
Additionally, why not just [encode once](https://github.com/textpattern/textpattern/issues/672#issuecomment-210395798), to avoid further trouble?

**Comment by Bloke** [comment] 2016-04-19 14:31
If `double_encode` works, then sure, employ it.

**Comment by rwetzlmayr** [comment] 2016-04-19 15:54
@bloatware:
> I don't think I have introduced a new escaping neither

My bad. Further investigation shows that it's been there since Jukka's initial commit of `join_atts` to the code base.

**Comment by bloatware** [comment] 2016-04-20 09:56
It should be mostly fixed by [9358ff5](https://github.com/textpattern/textpattern/commit/9358ff512bc42ff83e0772a9c04b2eede8c1a263), save for lonely `&` still being transformed into `&amp;`. We can keep the former `html_entity_decode()` (but it transformed e.g. `&nbsp;` into spaces, good thing?) or replace it with `htmlspecialchars_decode()` to fix it too.

**Comment by bloatware** [comment] 2016-04-20 10:34
And it breaks rss, great. Back to code

**Comment by rwetzlmayr** [comment] 2016-04-20 11:09
We have an inconsistency between *Recent articles* and *Content > Articles* lists and *title* when entities are used:

![txp-write-entities](https://cloud.githubusercontent.com/assets/357054/14672470/5490bee8-06f8-11e6-8628-48610fc985bf.png)

For comparison, in TXP 4.5.7 entities were decoded as the title got saved:

![txp-write-entities-457](https://cloud.githubusercontent.com/assets/357054/14672573/ff3c0f96-06f8-11e6-897a-85c199d4d4ec.png)


STR:

1. Create a new article literally titled `&#8220;FOO BAR&#8221;`.
1. Save this article.
1. In 4.6-dev: Notice that the title input shows the literal entities while the *recent articles* widget and the *article list* show the decoded characters.
1. In 4.5.7: Both the title input and the recent article list show decoded characters.

**Comment by bloatware** [comment] 2016-04-20 11:23
Yes, but I find this behaviour preferable. In 4.5.7, if we create some `Don't&nbsp;break&nbsp;me` title, it will (on the second async save) be transformed into literal `Don't break me`, which feels wrong, no?

**Comment by rwetzlmayr** [comment] 2016-04-20 11:37
> it will (on the second async save) be transformed into literal Don't break me

Cannot reproduce:

![dont-break-me](https://cloud.githubusercontent.com/assets/357054/14673214/e6ba07e4-06fc-11e6-8d7b-6990515c5141.png)

It doesn't feel wrong for me as I've been used to this behaviour for years.

**Comment by bloatware** [comment] 2016-04-20 12:10
If I do **two** consecutive async saves and reload the page, `&nbsp;` are gone (4.5.7)

**Comment by bloatware** [comment] 2016-04-28 11:16
Closed for me. If someone wants to restore the 4.5 behaviour, please feel free to reopen and patch.

**Closed by bloatware** 2016-04-28 11:16 UTC
Labels: Bug, Component: admin-side

**Comment by rwetzlmayr** [comment] 2016-04-28 11:36
Just to make sure: Do we now consider it good user experience that an article titled "Barnes & Noble" will be displayed as `Barnes &amp; Noble` after the initial save operation? 

To me this looks like our underwear is showing.

![bampn](https://cloud.githubusercontent.com/assets/357054/14884579/f640c7e4-0d45-11e6-8ae0-728824853059.png)

**Comment by bloatware** [comment] 2016-04-28 12:48
I wouldn't encode `&`, but (historically..) it's the only special char that is saved encoded in db. A plugin that presumes it could be broken if we drop the encoding. This said, I don't mind adding `html_specialchars_decode()` to the chain, but then `Barnes &amp; Noble` will be displayed as `Barnes & Noble`

**Comment by bloatware** [comment] 2016-04-29 09:17
[That](https://github.com/textpattern/textpattern/commit/f1bbebde416817136272aa93535c720a54ec9c90)'s my last offer, to please both `Barnes & Noble` and `All about "&amp;"` :) Anyone willing to restore the 4.5 behaviour is free to replace `preg_replace()` with `html_entity_decode()` in two `article_partial_title...()` functions.

**Comment by Bloke** [comment] 2016-05-03 15:22
Is this a suitable juncture to actually use the, currently empty, `Title_html` field in the `textpattern` table? Yes it would differ from 4.5.7's use as noted above and in #576, but for the sake of a one-time mass conversion at upgrade time if the `Title_html` field is empty, storing an encoded outwardly-presentable version of the Title and the admin-side raw version would neatly sidestep a lot of the headaches here.
