### ISSUE TITLE
Setting up a site - error(s)

### ISSUE THREAD

**Issue by phiw13** [textpattern/textpattern#587] opened 2015-11-08 01:27 UTC
Freshly git-fetched code base
I go through the routine, step 1, step 2,…
Create the required config.php inside /textpattern/ when asked:
(xxx for obfuscation…)

```
$txpcfg['db'] = 'txp45';
$txpcfg['user'] = ‘xxx’;
$txpcfg['pass'] = ‘xxx’;
$txpcfg['host'] = 'localhost';
$txpcfg['table_prefix'] = '';
$txpcfg['txpath'] = '/Users/xxx/Sites/_txp45/textpattern';
$txpcfg['dbcharset'] = 'utf8mb4';
```

Proceed with the next step (Creating database tables / user details)
Proceed to the last step

multiple lines of errors:

```
Notice: Undefined index: lang in /Users/xxx/Sites/_txp45/textpattern/setup/index.php on line 546
Notice: Undefined index: ddb in /Users/xxx/Sites/_txp45/textpattern/setup/index.php on line 611
Notice: Undefined index: ddb in /Users/xxx/Sites/_txp45/textpattern/setup/index.php on line 656
Notice: Undefined index: duser in /Users/xxx/Sites/_txp45/textpattern/setup/index.php on line 657
Notice: Undefined index: dpass in /Users/xxx/Sites/_txp45/textpattern/setup/index.php on line 658
Notice: Undefined index: dhost in /Users/xxx/Sites/_txp45/textpattern/setup/index.php on line 659
Notice: Undefined index: dclient_flags in /Users/xxx/Sites/_txp45/textpattern/setup/index.php on line 660
Notice: Undefined index: dprefix in /Users/xxx/Sites/_txp45/textpattern/setup/index.php on line 661
Notice: Undefined index: dbcharset in /Users/xxx/Sites/_txp45/textpattern/setup/index.php on line 663
```

Message:

```
(Error block) The contents of config.php do not match the values you entered. Please paste the exact text below.
```

Create config.php
Before you proceed: Create a file called config.php in the /textpattern/ directory and paste the following inside…

```
$txpcfg['db'] = '';
$txpcfg['user'] = '';
$txpcfg['pass'] = '';
$txpcfg['host'] = '';
$txpcfg['table_prefix'] = '';
$txpcfg['txpath'] = '/Users/xxx/Sites/_txp45/textpattern';
$txpcfg['dbcharset'] = ‘’;
```

Empty values, really?
I didn’t do anything, clicked the “I did it” button, only to reach the same screen… Sad trombone.

So. I go to `http://txp45.phiw.dev/textpattern` and there you have it: everybody’s favourite login screen. Enter name/pass and in we go…
And going to `//txp45.phiw.dev` loads “My site My pithy slogan” - surprise, not really. And checking The DB with Sequel Pro: all tables are there, afaict.

**Comment by phiw13** [comment] 2015-11-08 01:29
PS - OS X 10.11, Apache/2.4.16 (Unix) PHP/5.5.29, MySQL 5.6.21

**Comment by philwareham** [comment] 2015-11-08 09:11
Maybe something to do with the charset? I did a successful clean install a couple of days back from admin layout update branch but my charset was just UTF8 I think.

**Comment by Bloke** [comment] 2015-11-08 09:46
This'll happen if the `$_SESSION` is empty for some reason. Well need to investigate this, as the only time the session should be cleared/initialised is on the first step.

**Comment by phiw13** [comment] 2015-11-08 10:13
@Bloke 
Would it cause a problem with the @$_SESSION@ if I press the back button (actually a swipe from my mouse) between steps 2 and 3? I think I did that as, to my surprise, Safari/Keychain offered to save the MySQL name/password I had just entered.

**Comment by vanmelick** [comment] 2015-11-10 11:58
Perhaps the garbage collector cleaned up the session. What is the value of the ```session.gc_maxlifetime``` setting (php.ini)?

**Comment by phiw13** [comment] 2015-11-10 12:26
@vanmelick 

* `session.gc_maxlifetime = 1440`
* Creating the config.php probably took less than 2 minutes, I don’t remember how long threader I pressed the confirmation button, but it can’t be much.

**Comment by joopvos** [comment] 2015-11-10 12:50
I have the same problem, I think (http://goo.gl/DYbt6O). Going to /textpattern (http://joopvos.nl.greenhostpreview.nl/textpattern/) gives a 503 error: "internal_error "Table 'joopvos_nl.textpattern' doesn't exist" in /domains/joopvos.nl/DEFAULT/textpattern/lib/txplib_db.php at line 95". Is that of any help to solve this issue?

**Comment by vanmelick** [comment] 2015-11-10 13:36
Is there anything installed on your computer that could remove / block cookies during the setup process? Losing the session cookie would have this effect.

**Comment by phiw13** [comment] 2015-11-10 14:01
Not that I know. Ghostery is installed but has no effect on anything running on `localhost`. Ditto for my system wide ad blocker (Glimmerblocker, an http proxy). Safari is set to only allow cookies from current website, not a problem in this case, me thinks.

**Comment by joopvos** [comment] 2015-11-10 14:04
The techies have solved it by giving the sync process on the server (!?) more time. Step 1 (database) ... wait till sync has completed ... step 2 (config.php). It's not clear to me at all but it does have effect ... :)

**Comment by vanmelick** [comment] 2015-11-10 14:07
Did they say what it was they were syncing?

**Comment by joopvos** [comment] 2015-11-10 14:11
Ruud, I will ask ...

**Comment by Bloke** [comment] 2015-11-10 15:09
If there's a possibility that the garbage collector (or some third party tool) can interfere with the session then @phiw13's issue can be defended against in code by checking the session exists at each step of the wizard. But if we find no session data, what action do we take? Not very friendly to just throw you back to step 1 (although that's what is required), unless we can add an error display box there which could catch and show an informative reason for being dumped back to the start.

As for Joop's issue, ummm. If Google Translate has done its job properly, there appears to be a, possibly lengthy, delay between actual file upload of `config.php` and the file appearing in the correct location on the host. What I don't get is that if you happen to click 'I did it' before the file is uploaded, the setup wizard will (errr, should, last time I checked!) complain that the file doesn't exist. The lack of file does not explain the error message, afaict.

**Comment by vanmelick** [comment] 2015-11-10 15:46
IIRC, config.php on Joop's server does exist, but it apparently takes a short time for it to contain actual data. If config.php was missing, you'd get a different error. The mismatch error occurring here means that either config.php or $_SESSION doesn't contain what you expect. 
Perhaps @phiw13 has the same issue with config.php as Joop does. If so, I don't see any way to fix that, other than recommending reloading the page if this error occurs.

**Comment by vanmelick** [comment] 2015-11-10 15:58
IIRC, config.php on Joop's server does exist, but it apparently takes a short time for it to contain actual data. If config.php was missing, you'd get a different error. The mismatch error occurring here means that either config.php or $_SESSION doesn't contain what you expect.

Looking at the error messages @phiw13 is getting, it has to be related to $_SESSION. What I'd like to know is:

1. does the browser receive the session cookie after finishing step 1.
2. does the browser send the session cookie after finishing step 2.
3. does TXP see that session cookie
4. is there a session related to that cookie available.

@phiw13 can check the first two by looking at the HTTP headers in his browser (F12 => net => somewhere)

**Comment by Bloke** [comment] 2015-11-10 16:14
In Joop's case, if the file exists/is readable, there's a secondary check to see if it matches what we expect:

        if (!isset($txpcfg) || ($txpcfg['db'] != $_SESSION['ddb']) || ($txpcfg['table_prefix'] != $_SESSION['dprefix'])) {

If that fails it should throw a warning. Maybe this test needs to be extended a little to trap other possible scenarios?

If both tests pass, the only time it should complain about missing tables is when it gets to the 'doing stuff in the DB' step (i.e. step 4). This occurs after filling in the Txp admin user's credentials, which is usually quite a number of seconds further on from the upload process.

**Comment by vanmelick** [comment] 2015-11-10 17:48
@Bloke, I think that check did throw a warning in Joop's case ($txpcfg not set) and in @phiw13's case ($_SESSION['ddb'] doesn't exist so not equal to $txpcfg['db']).

There's a second issue in @phiw13's story: despite the error, the tables are created. Strange, because before displaying config.php to the user, TXP checks if the table exists. I wonder if this is reproducible and if there were multiple browser windows open in which the setup process was done on the same site (that would explain why the tables were created and why $_SESSION was empty).

**Comment by Bloke** [comment] 2015-11-10 20:12
Ah yes, I didn't spot Joop's screenshot. Thanks for the nudge, it makes more sense now.

As for the case of the missing `$_SESSION`, strange indeed. I ran a new installation today and it went smoothly but I haven't tried multiple tabs or anything like that to stress test the installer. Guess if it's not reproducible anywhere else we either:

* put it down to a random act of gremlins;
* see if it can be reproduced on @phiw13's server and try to find the root cause there, or;
* if we think it's a risk that might happen to others, put some defensive code at the start of each step of the wizard that checks if the session is set and bomb back to step 1 with a message if not.

**Comment by phiw13** [comment] 2015-11-11 01:06
Some random answers etc:

1. I went to the set up procedure again (other “domain name” on my mac’s server, new DB etc, up-to-date git-fetched code): This time I had no problem at all. **note**, though: I did not use (or open) Safari”s developer tools at any point in the process, I did not press the back button as I did at my previous attempt (original post above). Just straight click-click-click switch-to-text-editor and save file, etc.

2. @vanmelick  [comment](https://github.com/textpattern/textpattern/issues/587#issuecomment-155511819). I had Safari’s Developer tools (aka webkit inspector, a separate web process) open at one point, but closed it again IIRC. I didn’t *do* anything in that window though. Could it interfere with the`$_session` cookie ? I don’t think so (would kinda beat the purpose of the whole developer tools). And yes, I could go through the whole process till step 4 without Textpattern barfing. And there was certainly no delay between saving the `config.php` file and it appearing on the server, it is all the local file system.

3. @vanmelick  [comment](https://github.com/textpattern/textpattern/issues/587#issuecomment-155463474). I suppose/assume the cookie was set at each step / seen by TXP, but I have no way to know, several days after the fact.
After my successful install (see No1. above), I’ll try again, time allowing, while being hmm ‘naughty’ during the install process, and see if I can reproduce the issue.
I naively (?) would assume though that if the cookie contains unexpected data between each step, that the install process would complain.

4. @Bloke [comment](https://github.com/textpattern/textpattern/issues/587#issuecomment-155552149) (last point) - well yeah, that is why I filed this issue: to investigate if the install wizard can be strengthened to guard against (possible) user *mistakes* (me pressing the back button of the browser at one point).

**Comment by joopvos** [comment] 2015-11-16 10:14
It was a kernel bug (Linux) ... specific information was not shared by the provider.

**Comment by philwareham** [comment] 2015-11-18 08:51
Changed the title, since this seems not specific to the branch, rather the master.

**Comment by philwareham** [comment] 2016-03-23 09:41
Can anyone confirm whether this is still an issue or not?

**Comment by phiw13** [comment] 2016-04-22 12:47
I finally had the opportunity & time to run a test install and do some of the silly things I mentioned above (like me pressing the “back” button between any of the install steps). I did’t run into any problem this time.

**Comment by Bloke** [comment] 2016-04-22 12:52
Thanks for taking the time to re-test. Closing.

**Closed by Bloke** 2016-04-22 12:52 UTC
