### ISSUE TITLE
txp:css's "flat.link" format attribute returns the same value as "flat.url": which is the URL, not formatted as a link element

### ISSUE THREAD

**Issue by johnstephens** [textpattern/textpattern#1415] opened 2019-08-09 21:47 UTC
### Steps to reproduce

Enter this in a Textpattern template:

```
<txp:css format="flat.link" name="style_name" />
```

### Expected behaviour

I expect the flat.link function to wrap the URL in a link element, like so:

```
<link rel="stylesheet" type="text/css" href="https://example.com/css/example/style_name.css" />
```

### Actual behaviour

Instead, it returns the URL, without any HTML:

```
https://example.com/css/example/style_name.css
```

#### Additional information

Textpattern version: 4.7.3

**Comment by philwareham** [comment] 2019-08-10 07:59
This works as intended IMO.

**Comment by johnstephens** [comment] 2019-08-10 11:19
`format="link"` and `format="url"` give different results: The first wraps the URL in a link element, and the second returns the unformatted URL.

`format="flat.link"` and `format="flat.url"` are _intended_ to yield identical output? An unformatted URL?

If that's intended, why would there be two "flat" formats instead of one? If they are intended to yield identical output, it's confusing to use the "link" and "url" vocabulary, which yield separate and distinct results when called without the "flat." prefix.

**Comment by bloatware** [comment] 2019-08-10 14:09
`format="flat.link"` and `format="flat.url"` produce two different outputs for me. Are you sure your editing software has not inserted a space after the dot as they sometimes tend to do?

**Comment by johnstephens** [comment] 2019-08-10 18:44
I just typed this into a totally different site, also running Txp 4.7.3:

```
<!--
Link      : <txp:css format="link"/>
Url       : <txp:css format="url"/>
Flat.link : <txp:css format="flat.link"/>
Flat.url  : <txp:css format="flat.url"/>
-->
```
Here's what I got:

```
<!--
Link      : <link rel="stylesheet" media="screen" href="https://example.com/css/default/default.css" />
Url       : https://example.com/css/default/default.css
Flat.link : https://example.com/css/default/default.css
Flat.url  : https://example.com/css/default/default.css
-->
```
There was no editing software involved this time, and no spaces were inserted. I typically use Neovim, and it is not configured to insert junk after periods either.

I'm at a loss. What steps could I take to troubleshoot this?

**Comment by bloatware** [comment] 2019-08-10 20:15
I get this when copy-pasting, both on Pete's `release` [demo site](https://release-demo.textpattern.co/) and in my local `dev` branch:
```
<!--
Link      : <link rel="stylesheet" media="screen" href="http://localhost/textpattern/css.php?n=default&amp;t=four-point-seven" />

Url       : http://localhost/textpattern/css.php?n=default&amp;t=four-point-seven
Flat.link : <link rel="stylesheet" media="screen" href="http://localhost/textpattern/themes/four-point-seven/styles/default.css" />

Flat.url  : http://localhost/textpattern/themes/four-point-seven/styles/default.css
-->
```
No clue why you are always getting flat paths. What if you omit `format` attribute?

**Comment by cara-tm** [comment] 2019-08-11 08:33
May be off topic, but see also:

https://forum.textpattern.com/viewtopic.php?id=50338

**Comment by petecooper** [comment] 2021-02-14 17:29
Bumping this. @johnstephens – are you able to try the same code on a Textpattern 4.8 instance? I'm curious whether this is still happening on your side. Thanks!

**Comment by petecooper** [comment] 2021-03-23 10:40
Bumping. @johnstephens - are you able to test on 4.8.* and report back, please? Thanks!

**Comment by johnstephens** [comment] 2021-03-23 14:16
Thank you Pete! Sorry for the delay. I've been swamped lately, and I don't know when I'll have a chance to test this. I will report back ASAP when I get a chance to install 4.8.* and try it out.

**Comment by petecooper** [comment] 2023-12-22 23:50
If this is still relevant, let's take it back to the forum for more eyeballs.

Closing for now.

**Closed by petecooper** 2023-12-22 23:50 UTC
Labels: verification required
