### ISSUE TITLE
New articles erroneously marked as modified

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#762] opened 2016-09-10 19:14 UTC
Using 4.6.0, new articles appear to be marked as modified immediately after publishing.

STR: admin-side -> Content -> Write -> write content -> Publish -> Note status text below excerpt (using Hive theme).

Attached (work-safe) example uses the following body text to check posted/modified timestamps:

```
Published: <txp:posted />
Modified: <txp:modified />
```

[762-modified.mp4.zip](https://github.com/textpattern/textpattern/files/465598/762-modified.mp4.zip)

**Comment by Bloke** [comment] 2016-09-12 14:31
I suspect (no proof) this latest phenomenon might be the result of making queries cache-safe: see `now()` function at the bottom of `txplib_db.php` -- [relevant commit](https://github.com/textpattern/textpattern/commit/22e264ed). Article Posted column gets the timestamp of the time you loaded the Write panel. Modified gets the time you hit Publish. You can only make them the same by using the 'reset timestamp to now' checkbox.

This seems unexpected to me too, but maybe one of the others can shed some light on whether this is by design or an oversight.

See Issues [416](https://github.com/textpattern/textpattern/issues/416), [614](https://github.com/textpattern/textpattern/issues/614), [618](https://github.com/textpattern/textpattern/issues/618) and PRs [624](https://github.com/textpattern/textpattern/pull/624) and [629](https://github.com/textpattern/textpattern/pull/629) for historical discussions around this topic.

**Comment by bloatware** [comment] 2016-09-12 16:07
I agree, this looks like an oversight. The easiest patch seems to be setting "Set timestamp to now" checkbox for new articles checked by default.

**Comment by bloatware** [comment] 2016-09-12 17:30
Ahem... that's a really tiny patch that I would qualify as bugfix. Where do we submit them now? (hiding myself)

**Comment by philwareham** [comment] 2016-09-12 21:08
Hi Oleg, ok so as far as I know if this is for both 4.6 and 4.7 then branch off dev, then do the code, then pull request and merge to dev and also pull request and merge to master.

**Comment by bloatware** [comment] 2016-09-12 21:40
Hi Phil, I thought we pull bugfixes to master, without branching (nor tagging) for fewliners, and merge to dev? Will do it tomorrow if so.

**Comment by philwareham** [comment] 2016-09-12 21:43
@bloke can you enlighten us as to best practice here? :)

**Comment by Bloke** [comment] 2016-09-13 06:30
If it's a bugfix that's gonna be incorporated into the 4.6.x timeline, then yes patch on master and pull to dev afterwards so it's rolled into 4.7.

**Comment by bloatware** [comment] 2016-09-13 06:50
Thanks! Please test and close the issue if fixed. I will then pull it to dev.

**Comment by Bloke** [comment] 2016-09-13 08:18
Works for me. If you alter the date and uncheck the reset time checkbox, you get a modified timestamp of 'now', which is reasonable as it has technically been modified from the intended publication date, so I'm fine with that.

The only change in workflow is if you decide to alter the date prior to publication -- either into the past or future -- as you also need to uncheck the 'reset time' checkbox. Is there a case here for automatically unchecking the 'reset time' checkbox via jQuery if you alter any of the Posted boxes? Does that make sense? After all, by changing any of those you're stating "use the time I choose" so I think it's a reasonable assumption that you won't want the reset time box checked. If so, we might as well do it on the user's behalf to save a click / frustration.

**Comment by bloatware** [comment] 2016-09-13 08:48
Makes sense, but then I would rather leave Posted boxes empty and 'Set time' unchecked for new articles by default. The pre-filled values are not really pertinent here.

**Comment by Bloke** [comment] 2016-09-13 08:56
That would also work, as long as `txp_article.php` doesn't cry if you submit empty Posted fields. Give it a whirl if you like.

**Comment by bloatware** [comment] 2016-09-13 09:34
You are right, unchecking reset on timestamp change is better. Done (for files too), please retest.

**Comment by Bloke** [comment] 2016-09-13 10:14
Magic.

**Comment by bloatware** [comment] 2016-09-13 15:00
Gracias!  If you could throw now some of your (ma)git powder to resolve dev merge conflicts...

**Comment by Bloke** [comment] 2016-09-13 15:18
I'll take a look. This might be the point I realise that the dual-branch thing is rubbish and doesn't work, and we need to do what Phil suggested and have three. Fingers crossed...

**Comment by bloatware** [comment] 2016-09-14 13:19
Hopefully fixed, closing. Thanks @petecooper, @Bloke and @philwareham.

**Closed by bloatware** 2016-09-14 13:19 UTC
Labels: Bug, Component: admin-side, Priority: high

**Comment by petecooper** [comment] 2016-09-14 19:42
Thanks, @bloatware!
