### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1506] opened 2020-06-23 19:05 UTC
PHP 8.0 alpha 1 landed today, GA is scheduled for late November 2020: https://wiki.php.net/todo/php80

There are some issues with compatibility against the current @dev@ and @4.8.2@ branches, which is unsurprising given the big-ness of the release.

What's the feeling on preferred approach to resolve issues relating to PHP 8:

* start now/soon, one issue per error/warning
* start now/soon, one issue to triage multiple errors/warnings
* wait until after feature freeze and Beta 1 (August 2020)
* wait until RC 1 (September 2020)
* something else

@Bloke has a login to the demo server (and I'm happy for that to continue), so I'm not a single point of failure, but I'll do what I can to help with this.

**Comment by Bloke** [comment] 2020-06-23 19:43
If people are happy to report issues as normal (as long as we know the version of PHP targeted) and the bugs don't feature in the PHP bug tracker after a few days, then it's likely us that needs to change. Feel free to report any findings from now on. The good news is we're agile enough to be able to react to this, and it's a good talking point to have PHP-8 compatibility ahead of the game.

Most of the things I expect will be deprecation notices or things where they've tightened the type juggling. I know there are plenty of places in core, for example, where we declare a string variable then overwrite it with an array a bit later. It's not frowned upon - and it's a nice feature of PHP vs a strongly typed language - but it's bad form.

I suspect they'll start closing down these loopholes as the PHP team strive to give programmers a more rigid framework for their code that minimises the risk of injection attacks and buffer overruns via sloppy coding. Plus, we need to be sure that Txp continues to run under hosting environments that have been clamped down for 'safe' operation so we should keep an eye on what options they open up here.

Maybe long term we could compile a demo that runs in a PHP space with a host of restrictions in place? That'd be interesting to see how Txp behaves and if there's anything we can do to run under restrictive frameworks, since we're all about small footprint and light load for snappier performance. With WP and the like needing more and more resources with every version, it'd be nice to stamp ourselves with the 'also good for people on a server budget' rosette.

**Comment by Bloke** [comment] 2020-06-23 20:07
Upon further reading, some of the new features are nice-to-haves but we won't be using them as yet. We can move to typing parameters as we feel the need to abandon PHP 5 completely. The things that are likely to affect us:

* ext-json always available (Yay! But we still need to defend against it being not compiled in for PHP 5+7 support).
* Undefined variable: Error exception instead of notice. We _should_ be okay with this as most things we've caught in 4.8. Might be a few stragglers, and I can see older plugins breaking here unless they're patched.
* Undefined array index: warning instead of notice. Ditto.
* Creating default object from empty value: Error exception instead of warning. Not sure if this affects us or not, but potentially it might.
* Cannot use a scalar value as an array: Error exception instead of warning. This might hit us hard.
* Invalid argument supplied for foreach(): TypeError exception instead of warning. Ditto.
* Array to string conversion: warning instead of notice. Hopefully not in core, more for plugins I expect, but we may have missed some.
* Uninitialized string offset: %d: warning instead of notice. Again, might hit us but hopefully there aren't many left, as we've been mopping up uninitialized stuff recently.
* The @ operator no longer silences fatal errors. We should stamp out '@' in our code in deference to proper try{...} catch{} blocks. It's lazy coding.
* Default error reporting level E_ALL. This will likely popup warnings and notices that were previously silenced by our default error handling routines.
* Reflection method signature changes. Might hit us for Txp::get and the container interfaces may need a little tweaking.

**Closed** 2020-06-26 18:18 UTC
Labels: core

**Comment by petecooper** [comment] 2020-06-28 06:44
More bedtime reading - RFCs implemented in PHP 8.0: https://wiki.php.net/rfc#php_80

**Comment by rwetzlmayr** [comment] 2024-01-21 17:33
>     **Undefined variable: Error exception instead of notice.**

I've just hit an instance of a report that says _Warning: Undefined variable $pg on line 931_ caused by [this line](https://github.com/textpattern/textpattern/blob/b5c5c8465c99455246a1fa709a39dfb58fcb39a9/textpattern/publish.php#L931):

`$pg or $pg = 1;`

This line is obviously intended to deal with the "Undefined variable" case, but as of PHP 8 it causes a visible warning.

**Comment by Bloke** [comment] 2024-01-21 17:46
I happen to dislike the `something or something=start-value` construct intensely. And I don't know why, I just do.

It seems to be all the rage in JavaScript but it just comes across as, I dunno, a poor-man's initialisation workaround to me. I should probably move with the times and embrace it, but it never sits right with me.

I'm not advocating we stamp it out or anything in our code, but the way PHP is moving towards more strongly typed variables (as much as can be, in a scripting vs compiled language) this kind of construct is a warning waiting to happen if we, or somebody (or a plugin?) passes in something with a missing value, or unsets something upstream.

Should we try and avoid this construct in future, preferring dedicated initialisation or tests such as `empty()` which do not emit warnings?

**Comment by bloatware** [comment] 2024-01-21 18:32
This is not an initializer, `$pretext['pg']` must already be set, unless you call this function before `pretext()`, but then everything would go west.

**Comment by rwetzlmayr** [comment] 2024-01-22 00:53
It seems that a little context would help to understand why I hit this issue. Bear with me...

My plugin [catches](https://github.com/rwetzlmayr/wet_feditext/blob/350bf36cfd7fb977000ee5ea4724c926104b365e/wet_feditext.php#L129) the `pretext` event.

While [handling this event](https://github.com/rwetzlmayr/wet_feditext/blob/350bf36cfd7fb977000ee5ea4724c926104b365e/wet_feditext.php#L206), it calls `parse("<txp:article_custom ...")`; This finally runs `doArticles()` and throws this said warning.

So it seems to be running at a time when the `$pretext` array is already populated but not yet extracted. 

As the [callback](https://github.com/textpattern/textpattern/blob/b5c5c8465c99455246a1fa709a39dfb58fcb39a9/textpattern/publish.php#L200) for `pretext` is headed with a `// Request URI rewrite, anyone?` comment, while my plugin does some sort of URI rewriting that seemed to fit.

`pretext_end` also seems to be [called](https://github.com/textpattern/textpattern/blob/b5c5c8465c99455246a1fa709a39dfb58fcb39a9/textpattern/publish.php#L215) too early. 

Is there any other event I should catch to make my plugin work in PHP 8+ without throwing a warning? Please suggest!

**Comment by bloatware** [comment] 2024-01-22 09:55
Yep, this explains it, thanks. Most parts of `$pretext` are populated from URI, whence this comment for early plugins that do some rewriting. If at some point you also need `$pretext` to be populated, registering for a second callback on `pretext_end` looks natural.

Anyway, I've rewritten these bits more defensively, but it's certainly only the top of the iceberg.
