### ISSUE TITLE
Form names with exotic characters misbehave after upgrading from older versions

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1329] opened 2018-08-21 07:39 UTC
In the 4.4.x era, form names could start with `.`, `*` and other characters. In the 4.7.* era, they cannot.

Where a valid form name was used before, and the site is upgraded, the form name and content is unchanged in the database, but the form cannot be viewed in the Forms panel.

The name appears in the sidebar, but the content is not shown. Renaming to the form in the database to a valid name brings it back to life.

Safe for work screencast attached (no audio).

![screen shot 2018-08-21 at 08 33 38](https://user-images.githubusercontent.com/226578/44387497-9a876800-a51d-11e8-8f91-1776b679ac50.png)

[forms.zip](https://github.com/textpattern/textpattern/files/2305271/forms.zip)

**Comment by Bloke** [comment] 2018-12-07 09:52
I don't think there's much we can do about this, short of relaxing the rules to permit them to be viewed but not saved. We can't rename them to comply as that likely impacts the site templates.

@NicolasGraph, @bloatware do you think it's possible/a good idea to permit previously valid form names to still be _edited_ (seen) in the Forms panel, but if you try and save them without altering the name, it (correctly) warns you? Or even displays a warning near the 'name' box that the name doesn't comply and will need changing? Not sure.

What happens if you upgrade a site with invalid Form names and try to export the theme to disk? I seem to recall it gives warnings about files it cannot write due to bad names and they're skipped, so I think we're covered there.

One snag is that if we allow editing of such Forms, the names are sanitized without warning when you save. Try creating a Form in 4.7 with the name

```
.bob*&^£$/>@'"[+±§])!\}({;:,<|`~
```

It saves it successfully but the name is dumbed down to:

```
bob^£$@[+±§])!}({;,`~
```

Asterisk, ampersand, quotes, slashes, greater/less-than, colon and pipe are all ditched automatically (as they should) but is it better to at least throw an amber warning so people who go and save one at least notice the name has been changed?

**Comment by bloatware** [comment] 2018-12-07 10:20
I think we should permit viewing/editing such forms, but not saving unless the name is changed. A browser input pattern should suffice here, both for validation and warning (with a further validation server-side, of course).

**Comment by Bloke** [comment] 2018-12-07 10:23
Browser input pattern sounds like a great idea for the warning, plus server-side fallback. Do you have time to tackle this issue or shall I or Nicolas do it?

**Comment by bloatware** [comment] 2018-12-07 10:31
Please do, my free time is sporadic atm. I guess Pages and Styles would need it too.

**Comment by Bloke** [comment] 2018-12-10 11:36
This is harder than I thought on the server side. Making it accept old-style form names and showing the content is easy. The hard part is when saving.

The main issue is that the URL still holds the old name (`event=form&step=form_edit&name=.bob`) so the `gps()` looks at that first. Switching to `ps()` means clicking the Form names breaks and requires rework. Getting it to accept either the modified name (in the altered `$_POST` payload) or the one in the URL in the query is prone to error. And either method causes hassle when cloning as it doesn't auto-select the Form you just duplicated; you stay editing the old one, regardless if you renamed the Form first or let Txp add `_copy` to the name.

Hmmm.

**Comment by petecooper** [comment] 2018-12-10 11:38
Perhaps the solution is to have folks rename their forms & references to them _before_ upgrading? It has a whiff of edge case about it, as per with me.

**Comment by Bloke** [comment] 2018-12-10 12:23
True, we should mention this for completeness in the literature that nobody reads :p

But we should still be able to at least give people the ability to modify their old assets rather than refuse to admit they exist, imo. Diving into SQL to fix something like this after upgrade isn't something I'd relish on users - especially since it's not really any fault of their own.

**Comment by Bloke** [comment] 2018-12-17 23:15
Please would everyone stress-test branch [fix-1329](https://github.com/textpattern/textpattern/commit/3b05014541d316175f92015d86bc675705e545c4) and see if they can break it under both regular operation and extreme conditions. These include:

1) Duplicating forms, either with or without altering the name first.
2) Moving Forms to a different type.
3) Using custom Form types and different Themes.
4) Creating or duplicating Forms with existing names.
5) Trying to create invalid Form names.
6) Trying to save Forms that have invalid names and see if Txp dumbs them down correctly and issues a asuitable amber warning (use MySQL to alter an existing Form name to make it invalid, then try and edit it - you should be permitted to see it in the editor now, but when you save the Form, its name should be sanitized).
7) Trying to duplicate invalid Form names, with and without altering its name first vs letting Txp add `_copy` to it.
8) Any combination of the above.
9) Anything else you can think of.

Please be as devious as you can and check that the messages reported make sense, and the Form being edited after an operation is the correct one (i.e. if you duplicate that it immediately jumps to that Form for editing and sets the working Theme correctly). Please report breakages and steps to reproduce here.

One thing I've noticed:

The `pattern` regex Oleg committed the other day doesn't outlaw preceding dots. So a Form name `.article` or `../article` can be created, although they'll both be sanitized to just `article`. If, however, you try and use any other illegal characters (e.g. `.article"^^`) the browser should reject them as not matching the filter pattern and not let you save at all. Dots within the Form name are valid, btw, just not at the start.

If anyone has any improvements that can be made to this patch, please do so. It seems kinda hacky to me. Either way, whatever mechanism we settle on here for Forms needs to be rolled out to Pages and Styles and thoroughly tested ASAP.

Thank you in advance.

**Comment by petecooper** [comment] 2018-12-17 23:21
Nice one, @Bloke - thanks for this. I've switched the dev demo site to use `fix-1329` and I've forced a rebuild so as of now it'll be refreshing every three hours as before. If/when you're happy with the fix, I'll switch it back to `dev` branch instead.

**Comment by Bloke** [comment] 2018-12-17 23:32
They're limited to 63 chars, and so is the database index. They should truncate, but if you start to approach that you'll see `Duplicate  Index` error messages in debugging mode if you try and duplicate a really long Form name, because it'll try and create a name-theme index with the same name as the original Form.

**Comment by Bloke** [comment] 2018-12-17 23:43
Mmmmm, tasty:
```
UPDATE txp_form SET name='.bob^£$''@\\[+"±<>§])!}({;,`~' where name='some-form-you-no-longer-need';
```

Seems to handle it okay and when you remove the bad chars like quote, apostrophe and angle brackets to satisfy the browser's pattern (interestingly, backslashes seem to be okay too) it saves fine - dumbed down - without the preceding dot and other now-illegal chars.

You can also use the browser inspector to remove the `pattern` attribute on the `newname` field so you can put all manner of weird chars in and see what happens server-side when you save.

**Comment by petecooper** [comment] 2018-12-17 23:48
>Trying to create invalid Form names.

Anything here that's notable, @Bloke ?

<img width="376" alt="screen shot 2018-12-17 at 23 47 24" src="https://user-images.githubusercontent.com/226578/50122827-3750dc80-0256-11e9-8c30-f9e8660e3ccc.png">

**Comment by Bloke** [comment] 2018-12-17 23:59
Great ideas for stress tests. They all seem to behave here. Hopefully these will give people ideas for other corner cases to try (love the `Drop table...` one!)

I also removed the browser input pattern and tried to rename a Form as `&foo=bar` in case clicking on it to edit would invalidate the URL but Txp correctly sanitized out the ampersand. W00t.

**Comment by petecooper** [comment] 2018-12-18 00:02
>Hopefully these will give people ideas for other corner cases to try

I can't decide whether paging @phiw13 will hinder or assist in his recovery, but here goes…

**Comment by Bloke** [comment] 2018-12-18 11:06
I've done the same for Pages and Styles in commit bffef2e. Please test with the same rigour as the patch for Forms, thank you.

**Comment by bloatware** [comment] 2018-12-18 11:42
Looks good. We could also tidy the input pattern, borrowing it from `sanitizeForFile` function, but thoroughly reproducing the admin-side sanitation seems complicated.

**Comment by Bloke** [comment] 2018-12-18 11:59
Yeah, it's not vital to replicate the server-side sanitization pattern. The thing gets cleaned anyway and the pattern you put in catches the big players.

One thing I found. Not sure if this is a bug in implementation or if we can live with it:

1) Create a new Page/Form/Style.
2) Give it the name `../test-thing`.
3) Enter any content.
4) Save.

ER: an amber warning that the asset has saved, because the name has been auto-sanitized to `test-thing`.

AR: A green success alert that the asset has saved with the sanitized name.

If you edit and save an existing asset with an old name, the amber warning is issued, but not if you create a new one that has an invalid name. The logic for 'copy' and 'new' is intertwined so unpicking it might be more hassle than it's worth. Also, the check for `$passedName !== $name` in the 'insert' branch might be wrong, but it's also run if you duplicate an asset and I think it works under those conditions.

Not sure what to do about it, if anything.

**Comment by petecooper** [comment] 2018-12-18 12:30
@Bloke - your changes seem sound to me, though I haven't extensively tested from oooold versions.

What's your current take on this - further testing from the user base needed? Defer any changes until post-4.7.2? Looking at `HISTORY.txt` there are more than enough fixes and changes in place to justify a version bump, in my humble opinion.

**Comment by Bloke** [comment] 2018-12-18 12:49
> Let's tighten the pattern

Cool. Wanna do the honours, assuming browsers interpret regexes equally?!

> Defer any changes until post-4.7.2?

I think  we can go with it as 4.7.2. Although we've introduced seemingly "new" things, they're all arguably refinements to what we introduced in 4.7.0 and 4.7.1, making them better, more robust and useful. So a patch version bump is perfectly adequate.

**Comment by petecooper** [comment] 2018-12-18 12:55
>I think we can go with it as 4.7.2.

Thumbs up. I'll switch the dev demo back to `dev` branch for completeness.

**Comment by bloatware** [comment] 2018-12-18 13:02
> assuming browsers interpret regexes equally

I have tried it in IE and it works, no need to test any further. Just incorporate it in your branch before merging, perhaps?

**Comment by Bloke** [comment] 2018-12-18 13:31
Awesome, thanks for the regex. Committed, merged and pushed to dev.

**Closed** 2018-12-18 13:39 UTC
Labels: Forms, Upgrading
