### ISSUE TITLE
Errors when no 'styles' directory in theme on import, or on export with no style recorded

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern#1538] opened 2020-08-14 13:04 UTC
Related to: https://github.com/textpattern/textpattern/issues/1537

### Expected behaviour

Since we can remove styles complete from a section and site, the default style can be deleted. That is good, because some users will keep their styles in a separate assets folder in root or from a CDN, or wherever they like.

### Actual behaviour

However, if you then try to export the theme to disk, or vice versa if you try to import a theme that has no `styles` directory, The system gives you error messages. The import/export does seem to work though (although an empty `styles` directory is made on export).

We need to build in support for the above workflow, so it's not seen as an error.

#### Additional information

Textpattern version: 4.8.3, 4.9

**Comment by bloatware** [comment] 2020-08-14 13:43
We have `default` style hard-coded in core. Wouldn't it be logical to protect it from deletion, as we do for pages and forms?

**Comment by philwareham** [comment] 2020-08-14 13:44
Yes, that would also resolve these two issue.

**Comment by philwareham** [comment] 2020-08-14 13:57
@bloatware although `default` has never been protected against deletion before (you can change it's name to whatever you like). This problem has only arisen now because (I believe) previously you couldn't assign a style of 'none' to a section. So there was never a situation where you could delete all the stylesheets as at least one was always being used.

**Comment by bloatware** [comment] 2020-08-14 14:25
@philwareham yes, you can rename it, though txp still expects it to be there, e.g. in `<txp:css name="" />`. Certainly, we should remove these assumptions (for forms and pages too) when we can, but I'm a bit uncomfortable doing it in 4.8.3 at the risk of new bugs.

**Comment by philwareham** [comment] 2020-08-14 14:35
Sure, short-term I think we just need to ensure that at least one style is always there (i.e. the system won't let you delete *all* stylesheets). That will quickly resolve this issue.

**Comment by bloatware** [comment] 2020-08-14 15:53
I guess we can already remove error messages, since export/import should work anyway. Or transform them into 'warning' rather than 'error'.

**Comment by bloatware** [comment] 2020-08-14 21:49
Styles export/import with sync gives rather strange results in my tests. On export, `styles` subdirectory is simply deleted. On import, if there is no `styles` subdirectory, no style is deleted from db. And the code is way too complicated for my debugging skills.

**Comment by Bloke** [comment] 2020-08-16 12:55
I suppose this could (in theory...) happen to Pages but I'm not sure anyone would intentionally delete them all and serve solely pageless content on a site. Styles are a bit of an anomaly because we allow the database to be bypassed and the asset served from disk/theme.

I concur that we just prevent the last one being deleted outright, regardless of what it's called. If you don't use the database copy, empty the contents or put a comment in that says "see disk" or something.

**Comment by philwareham** [comment] 2020-08-16 12:58
I don’t think you can delete all pages can you. Error_default can’t be deleted IIRC.

**Comment by Bloke** [comment] 2020-08-16 13:23
Good point.

**Comment by bloatware** [comment] 2020-08-16 13:32
I'm more annoyed with [this](https://github.com/textpattern/textpattern/issues/1538#issuecomment-674286293), since the whole `styles` folder is deleted when I try to export a theme with sync. Is it only me?

**Comment by Bloke** [comment] 2020-08-16 13:39
Yeah, that is kind of annoying. I haven't tested it yet - I'll try and do so later today. Would half this be solved by not permitting the last style to be deleted form the DB? Then there's at least _something_ there to sync?

On import, if memory serves it's meant to put a default (empty, with comment) style in place if you import an empty/non-existent directory. Maybe it's not doing that any more. Or the sync is being bypassed because the dir is empty. Smells of an incorrect 'empty' vs 'non-existent' / empty() vs isset() test.

**Comment by bloatware** [comment] 2020-08-16 14:10
Sorry, that was me. I have a custom `css` media-type, removing it solves the folder deletion problem. I suspect that txp file names comparison is fooled by registered `.css` extension. Will try to debug.

**Comment by Bloke** [comment] 2020-08-16 14:16
Ah, intriguing. I was quite certain that Nicolas put in some defensive code for empty dirs. Glad you found the culprit.

**Comment by bloatware** [comment] 2020-08-16 16:19
I'm not sure they are/should be protected, but deleting empty folders is ok since they are recreated when necessary. The problem is our ulterior custom types addendum which does not fit the initial code very well. Not only styles are concerned. Try to create
```
[txp]
mediatype="text/plain"
```
custom form type and export a theme with sync - `pages` dir and all subdirs of `forms` are deleted.

**Comment by petecooper** [comment] 2020-08-17 08:54
Tagging https://github.com/textpattern/textpattern/issues/1534 as a requirement for 4.8.3

**Comment by bloatware** [comment] 2020-08-17 09:27
I guess our (my) error was making `$mimetypes` member of the base class, rather than of `Forms`, but refactoring/testing this can take time. I know though how to dirty-patch the `sync` issue, if we don't want to delay 4.8.3.

**Comment by Bloke** [comment] 2020-08-17 09:28
I'm happy with whatever needs to happen. If we need a week or so extra testing, so be it.

**Comment by petecooper** [comment] 2020-08-17 09:30
>If we need a week or so extra testing, so be it.

Heavy +1, especially since this might be the last patch of this release series.

**Comment by bloatware** [comment] 2020-08-17 15:03
Delete on sync issue should be mainly fixed now, save for `txp` custom form type, but one shouldn't create it anyway.

I would postpone styles-specific issues to 4.9. I actually don't see why we should treat `css` assets differently from, say, `js`. In 4.9 we could merge them into forms and simplify the interface.

**Comment by Bloke** [comment] 2020-08-17 15:48
That's interesting. I know Ruud a long time ago posited removing Forms in favour of Pages (or vice versa) because they do the same thing. This is kind of a similar argument, just differentiating on _media type_.

The main reason I can see for keeping stylesheets separate is the ingrained workflow with the Sections panel at present. And that a lot of internal code assumes a stylesheet exists, or at least fetches one from that table. There'd be a fair bit of refactorisation to fetch them from the Forms panel with type='css'.

Would this spell the end for assigning a style to a section? How would that affect the `<txp:css>` tag? Or would we present a list of Forms of the 'stylesheet' media type here instead and wire up the tag to read from here instead?

Not averse to rethinking stuff. Just gotta be for the right reasons.

**Comment by bloatware** [comment] 2020-08-17 16:14
Serving styles via txp looks expensive: launch php, fetch from db. They are not processed anyway, so direct file links would suffice, and actually are more and more common in txp community. If we merge styles in forms, we get both options: flat files for static styles and parsed ones if you wish.

Pages are a different story, since they should not be directly accessible but bound to sections, for some security reasons Jukka only knows.

**Comment by Bloke** [comment] 2020-08-17 17:12
> Serving styles via txp looks expensive: launch php, fetch from db.

True.

> They are not processed anyway, so direct file links would suffice, and actually are more and more common in txp community.

Absolutely. Would we rewire `<txp:css />` to serve a static link to a file instead of via css.php/publish.php? i.e. would you still envision we allow people to associate a stylesheet (from a subset of Forms) in the Sections panel and have `<txp:css />` serve the assigned asset, if defined? With the alternative being to serve any sheet give its `name` for the current theme in force (dev or live).

There are a few (minor) downsides:

* The asset _must_ be exported before it can be used. This makes it difficult to offer an out-of-the-box experience, since our /themes directory is empty, by design, to assist upgraders. So after installation, you would have to manually export the theme in use before you could see the stylesheet applied to the website. Otherwise, `<txp:css>` would render nothing, right? Or would it read the contents from `txp_forms` if the file doesn't exist?
* The above breaks our nice convention of "stuff in the DB is the last word". We're now saying "all template stuff is fetched from the database, except styles which are fetched from disk."
* It also means if you export a database dump, you don't necessarily have everything in one place. I know images and files are separate, but they always have been due to their potential size. If you dump a database and transfer it, you've also now got to include the `/theme/theme-name/forms/styles/stylsheet.css` if you want an accurate representation of your site.
* The 'Export to disk' checkbox is not retained as you move around from panel to panel or asset to asset. That'd be super annoying here. It's bad enough if you (like me recently) have been working with a disk-based asset but editing it in the CMS admin panel. The number of times I've taken the content from the web inspector after making a change, pasted it in and then scratched my head why it's made no difference is unreal. Then checked the Export button and re-saved after a 'lightbulb' moment.

>If we merge styles in forms, we get both options: flat files for static styles and parsed ones if you wish.

That is a powerful feature indeed. This is well worthy of consideration if we can accomplish it.

**Comment by bloatware** [comment] 2020-08-17 17:32
In no particular order:

- `<txp:css format="flat.link" />` already serves static links.
- we can already serve parsed `css` files, either via creating `text/css` media-type forms, or setting headers via `<txp:header />`.
- forms are still stored in db, so 'future' styles will be too. You don't have to export them to disk if it's ok to serve from db. They just move from `txp_css` table to `txp_forms`, so dumping db for export is still ok.
- one day we might want to implement à-la `etc_flat` functionality in core, which makes all assets face this db/disk sync problem.

I don't say it's trivial, but we can accomplish it.

**Comment by petecooper** [comment] 2020-08-20 15:08
Do we need to encourage user testing on this? I think this is the only open issue in the 4.8.3 queue at the moment.

**Comment by Bloke** [comment] 2020-08-20 15:33
Yes, I think so. Didn't get a chance to grill it the other night. I should do so as well.

**Comment by petecooper** [comment] 2020-08-20 16:02
Alright, cool - I'll put some words together tonight for the forum and possibly eager socials readers, see what happens

**Comment by petecooper** [comment] 2020-08-20 18:36
Done - https://forum.textpattern.com/viewtopic.php?pid=325506#p325506

Pile in as you see fit, corrections and clarifications always welcome.

**Comment by gud0** [comment] 2020-08-24 08:11
From my viewpoint as a theme maker, my latest themes were much easier to install and write instructions for because I used the Styles folder. I put an img and font folder in there as well as stylesheets. It seemed the best place to put them so they don't get zapped and for ease of reference from the stylesheet. Perhaps other theme makers would do something similar, so there'd always be a need for a styles folder?

**Comment by petecooper** [comment] 2020-08-26 05:58
Tagging https://forum.textpattern.com/viewtopic.php?pid=325569#p325569 for investigation.

**Comment by petecooper** [comment] 2020-09-08 08:08
Successful test: https://forum.textpattern.com/viewtopic.php?pid=325837#p325837

**Comment by petecooper** [comment] 2020-09-10 11:29
Are we mostly or entirely happy this is resolved, sirs?

**Comment by philwareham** [comment] 2020-09-10 11:40
I am entirely happy

**Comment by bloatware** [comment] 2020-09-10 11:47
I'm 4.8.3-happy

**Closed** 2020-09-10 14:52 UTC
Labels: bug :bug:, themes
