### ISSUE TITLE
Erroneous (?) placement of message dialogs on admin-side

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern#1622] opened 2021-01-03 11:31 UTC
### Expected behaviour

Message dialog to appear bottom middle of the browser viewport.

### Actual behaviour

Message dialog appears bottom left of the browser viewport.

### Steps to reproduce

* https://dev-demo.textpattern.co/dev/textpattern/index.php
* do something to trigger a message dialog (save, publish etc)
* note placement of confirmation / warning / error:

![Screenshot 2021-01-03 at 11 23 17](https://user-images.githubusercontent.com/226578/103477423-b28e7800-4db6-11eb-8d78-eba310794092.png)
![Screenshot 2021-01-03 at 11 23 27](https://user-images.githubusercontent.com/226578/103477425-b5896880-4db6-11eb-9253-9f13a8f373ea.png)

Seems to affect 'Hive' and 'Hive (Neutral)', 'Classic' not affected.

#### Additional information

Textpattern version: current `dev` as of 0900 CET today.

Web server vendor and version: Nginx 1.19

Database server vendor and version: Percona 8.0

PHP version: 8.0

**Comment by Bloke** [comment] 2021-01-03 11:59
I think that's by design as Phil's moved the stuff around for the fixed lower save button on mobile. Check with @philwareham

**Comment by petecooper** [comment] 2021-01-03 12:14
Ah, OK - thanks @Bloke, wasn't sure, hence title.

**Comment by philwareham** [comment] 2021-01-03 13:52
Yep, that's changed by design. I haven't finished the consistent save zones and surrounding UI just yet though. Closing this as there is already an open issue for the UI changes. Ta!

**Closed by philwareham** 2021-01-03 13:52 UTC
Labels: admin-side, usability / UI / UX
